// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cheat.proto

#include "Cheat.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR CS_CreateItemCheatPacket::CS_CreateItemCheatPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.itemseq_)*/0
  , /*decltype(_impl_.userseq_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CS_CreateItemCheatPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_CreateItemCheatPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_CreateItemCheatPacketDefaultTypeInternal() {}
  union {
    CS_CreateItemCheatPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_CreateItemCheatPacketDefaultTypeInternal _CS_CreateItemCheatPacket_default_instance_;
PROTOBUF_CONSTEXPR CS_CreateSkillCheatPacket::CS_CreateSkillCheatPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.skillseq_)*/0
  , /*decltype(_impl_.userseq_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CS_CreateSkillCheatPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_CreateSkillCheatPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_CreateSkillCheatPacketDefaultTypeInternal() {}
  union {
    CS_CreateSkillCheatPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_CreateSkillCheatPacketDefaultTypeInternal _CS_CreateSkillCheatPacket_default_instance_;
PROTOBUF_CONSTEXPR CS_CreateMonsterCheatPacket::CS_CreateMonsterCheatPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mapid_)*/int64_t{0}
  , /*decltype(_impl_.channelid_)*/int64_t{0}
  , /*decltype(_impl_.monsterseq_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CS_CreateMonsterCheatPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_CreateMonsterCheatPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_CreateMonsterCheatPacketDefaultTypeInternal() {}
  union {
    CS_CreateMonsterCheatPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_CreateMonsterCheatPacketDefaultTypeInternal _CS_CreateMonsterCheatPacket_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Cheat_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Cheat_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Cheat_2eproto = nullptr;

const uint32_t TableStruct_Cheat_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateItemCheatPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateItemCheatPacket, _impl_.itemseq_),
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateItemCheatPacket, _impl_.userseq_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateSkillCheatPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateSkillCheatPacket, _impl_.skillseq_),
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateSkillCheatPacket, _impl_.userseq_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateMonsterCheatPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateMonsterCheatPacket, _impl_.monsterseq_),
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateMonsterCheatPacket, _impl_.mapid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_CreateMonsterCheatPacket, _impl_.channelid_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::CS_CreateItemCheatPacket)},
  { 8, -1, -1, sizeof(::Protocol::CS_CreateSkillCheatPacket)},
  { 16, -1, -1, sizeof(::Protocol::CS_CreateMonsterCheatPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_CS_CreateItemCheatPacket_default_instance_._instance,
  &::Protocol::_CS_CreateSkillCheatPacket_default_instance_._instance,
  &::Protocol::_CS_CreateMonsterCheatPacket_default_instance_._instance,
};

const char descriptor_table_protodef_Cheat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013Cheat.proto\022\010Protocol\"<\n\030CS_CreateItem"
  "CheatPacket\022\017\n\007itemSeq\030\001 \001(\005\022\017\n\007userSeq\030"
  "\002 \001(\005\">\n\031CS_CreateSkillCheatPacket\022\020\n\010sk"
  "illSeq\030\001 \001(\005\022\017\n\007userSeq\030\002 \001(\005\"S\n\033CS_Crea"
  "teMonsterCheatPacket\022\022\n\nmonsterSeq\030\001 \001(\005"
  "\022\r\n\005mapId\030\002 \001(\003\022\021\n\tchannelId\030\003 \001(\003b\006prot"
  "o3"
  ;
static ::_pbi::once_flag descriptor_table_Cheat_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Cheat_2eproto = {
    false, false, 242, descriptor_table_protodef_Cheat_2eproto,
    "Cheat.proto",
    &descriptor_table_Cheat_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_Cheat_2eproto::offsets,
    file_level_metadata_Cheat_2eproto, file_level_enum_descriptors_Cheat_2eproto,
    file_level_service_descriptors_Cheat_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Cheat_2eproto_getter() {
  return &descriptor_table_Cheat_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Cheat_2eproto(&descriptor_table_Cheat_2eproto);
namespace Protocol {

// ===================================================================

class CS_CreateItemCheatPacket::_Internal {
 public:
};

CS_CreateItemCheatPacket::CS_CreateItemCheatPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_CreateItemCheatPacket)
}
CS_CreateItemCheatPacket::CS_CreateItemCheatPacket(const CS_CreateItemCheatPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CS_CreateItemCheatPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.itemseq_){}
    , decltype(_impl_.userseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.itemseq_, &from._impl_.itemseq_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.userseq_) -
    reinterpret_cast<char*>(&_impl_.itemseq_)) + sizeof(_impl_.userseq_));
  // @@protoc_insertion_point(copy_constructor:Protocol.CS_CreateItemCheatPacket)
}

inline void CS_CreateItemCheatPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.itemseq_){0}
    , decltype(_impl_.userseq_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CS_CreateItemCheatPacket::~CS_CreateItemCheatPacket() {
  // @@protoc_insertion_point(destructor:Protocol.CS_CreateItemCheatPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CS_CreateItemCheatPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CS_CreateItemCheatPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CS_CreateItemCheatPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_CreateItemCheatPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.itemseq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.userseq_) -
      reinterpret_cast<char*>(&_impl_.itemseq_)) + sizeof(_impl_.userseq_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CS_CreateItemCheatPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 itemSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.itemseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 userSeq = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CS_CreateItemCheatPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_CreateItemCheatPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 itemSeq = 1;
  if (this->_internal_itemseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_itemseq(), target);
  }

  // int32 userSeq = 2;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_userseq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_CreateItemCheatPacket)
  return target;
}

size_t CS_CreateItemCheatPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CS_CreateItemCheatPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 itemSeq = 1;
  if (this->_internal_itemseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_itemseq());
  }

  // int32 userSeq = 2;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_userseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CS_CreateItemCheatPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CS_CreateItemCheatPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CS_CreateItemCheatPacket::GetClassData() const { return &_class_data_; }


void CS_CreateItemCheatPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CS_CreateItemCheatPacket*>(&to_msg);
  auto& from = static_cast<const CS_CreateItemCheatPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_CreateItemCheatPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_itemseq() != 0) {
    _this->_internal_set_itemseq(from._internal_itemseq());
  }
  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CS_CreateItemCheatPacket::CopyFrom(const CS_CreateItemCheatPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_CreateItemCheatPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_CreateItemCheatPacket::IsInitialized() const {
  return true;
}

void CS_CreateItemCheatPacket::InternalSwap(CS_CreateItemCheatPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CS_CreateItemCheatPacket, _impl_.userseq_)
      + sizeof(CS_CreateItemCheatPacket::_impl_.userseq_)
      - PROTOBUF_FIELD_OFFSET(CS_CreateItemCheatPacket, _impl_.itemseq_)>(
          reinterpret_cast<char*>(&_impl_.itemseq_),
          reinterpret_cast<char*>(&other->_impl_.itemseq_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CS_CreateItemCheatPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Cheat_2eproto_getter, &descriptor_table_Cheat_2eproto_once,
      file_level_metadata_Cheat_2eproto[0]);
}

// ===================================================================

class CS_CreateSkillCheatPacket::_Internal {
 public:
};

CS_CreateSkillCheatPacket::CS_CreateSkillCheatPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_CreateSkillCheatPacket)
}
CS_CreateSkillCheatPacket::CS_CreateSkillCheatPacket(const CS_CreateSkillCheatPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CS_CreateSkillCheatPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.skillseq_){}
    , decltype(_impl_.userseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.skillseq_, &from._impl_.skillseq_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.userseq_) -
    reinterpret_cast<char*>(&_impl_.skillseq_)) + sizeof(_impl_.userseq_));
  // @@protoc_insertion_point(copy_constructor:Protocol.CS_CreateSkillCheatPacket)
}

inline void CS_CreateSkillCheatPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.skillseq_){0}
    , decltype(_impl_.userseq_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CS_CreateSkillCheatPacket::~CS_CreateSkillCheatPacket() {
  // @@protoc_insertion_point(destructor:Protocol.CS_CreateSkillCheatPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CS_CreateSkillCheatPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CS_CreateSkillCheatPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CS_CreateSkillCheatPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_CreateSkillCheatPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.skillseq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.userseq_) -
      reinterpret_cast<char*>(&_impl_.skillseq_)) + sizeof(_impl_.userseq_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CS_CreateSkillCheatPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 skillSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.skillseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 userSeq = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CS_CreateSkillCheatPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_CreateSkillCheatPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 skillSeq = 1;
  if (this->_internal_skillseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_skillseq(), target);
  }

  // int32 userSeq = 2;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_userseq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_CreateSkillCheatPacket)
  return target;
}

size_t CS_CreateSkillCheatPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CS_CreateSkillCheatPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 skillSeq = 1;
  if (this->_internal_skillseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_skillseq());
  }

  // int32 userSeq = 2;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_userseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CS_CreateSkillCheatPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CS_CreateSkillCheatPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CS_CreateSkillCheatPacket::GetClassData() const { return &_class_data_; }


void CS_CreateSkillCheatPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CS_CreateSkillCheatPacket*>(&to_msg);
  auto& from = static_cast<const CS_CreateSkillCheatPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_CreateSkillCheatPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_skillseq() != 0) {
    _this->_internal_set_skillseq(from._internal_skillseq());
  }
  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CS_CreateSkillCheatPacket::CopyFrom(const CS_CreateSkillCheatPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_CreateSkillCheatPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_CreateSkillCheatPacket::IsInitialized() const {
  return true;
}

void CS_CreateSkillCheatPacket::InternalSwap(CS_CreateSkillCheatPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CS_CreateSkillCheatPacket, _impl_.userseq_)
      + sizeof(CS_CreateSkillCheatPacket::_impl_.userseq_)
      - PROTOBUF_FIELD_OFFSET(CS_CreateSkillCheatPacket, _impl_.skillseq_)>(
          reinterpret_cast<char*>(&_impl_.skillseq_),
          reinterpret_cast<char*>(&other->_impl_.skillseq_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CS_CreateSkillCheatPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Cheat_2eproto_getter, &descriptor_table_Cheat_2eproto_once,
      file_level_metadata_Cheat_2eproto[1]);
}

// ===================================================================

class CS_CreateMonsterCheatPacket::_Internal {
 public:
};

CS_CreateMonsterCheatPacket::CS_CreateMonsterCheatPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_CreateMonsterCheatPacket)
}
CS_CreateMonsterCheatPacket::CS_CreateMonsterCheatPacket(const CS_CreateMonsterCheatPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CS_CreateMonsterCheatPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.mapid_){}
    , decltype(_impl_.channelid_){}
    , decltype(_impl_.monsterseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.mapid_, &from._impl_.mapid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.monsterseq_) -
    reinterpret_cast<char*>(&_impl_.mapid_)) + sizeof(_impl_.monsterseq_));
  // @@protoc_insertion_point(copy_constructor:Protocol.CS_CreateMonsterCheatPacket)
}

inline void CS_CreateMonsterCheatPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.mapid_){int64_t{0}}
    , decltype(_impl_.channelid_){int64_t{0}}
    , decltype(_impl_.monsterseq_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CS_CreateMonsterCheatPacket::~CS_CreateMonsterCheatPacket() {
  // @@protoc_insertion_point(destructor:Protocol.CS_CreateMonsterCheatPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CS_CreateMonsterCheatPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CS_CreateMonsterCheatPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CS_CreateMonsterCheatPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_CreateMonsterCheatPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.mapid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.monsterseq_) -
      reinterpret_cast<char*>(&_impl_.mapid_)) + sizeof(_impl_.monsterseq_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CS_CreateMonsterCheatPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 monsterSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.monsterseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 mapId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.mapid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 channelId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.channelid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CS_CreateMonsterCheatPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_CreateMonsterCheatPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 monsterSeq = 1;
  if (this->_internal_monsterseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_monsterseq(), target);
  }

  // int64 mapId = 2;
  if (this->_internal_mapid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_mapid(), target);
  }

  // int64 channelId = 3;
  if (this->_internal_channelid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_channelid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_CreateMonsterCheatPacket)
  return target;
}

size_t CS_CreateMonsterCheatPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CS_CreateMonsterCheatPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 mapId = 2;
  if (this->_internal_mapid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_mapid());
  }

  // int64 channelId = 3;
  if (this->_internal_channelid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_channelid());
  }

  // int32 monsterSeq = 1;
  if (this->_internal_monsterseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_monsterseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CS_CreateMonsterCheatPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CS_CreateMonsterCheatPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CS_CreateMonsterCheatPacket::GetClassData() const { return &_class_data_; }


void CS_CreateMonsterCheatPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CS_CreateMonsterCheatPacket*>(&to_msg);
  auto& from = static_cast<const CS_CreateMonsterCheatPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_CreateMonsterCheatPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_mapid() != 0) {
    _this->_internal_set_mapid(from._internal_mapid());
  }
  if (from._internal_channelid() != 0) {
    _this->_internal_set_channelid(from._internal_channelid());
  }
  if (from._internal_monsterseq() != 0) {
    _this->_internal_set_monsterseq(from._internal_monsterseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CS_CreateMonsterCheatPacket::CopyFrom(const CS_CreateMonsterCheatPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_CreateMonsterCheatPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_CreateMonsterCheatPacket::IsInitialized() const {
  return true;
}

void CS_CreateMonsterCheatPacket::InternalSwap(CS_CreateMonsterCheatPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CS_CreateMonsterCheatPacket, _impl_.monsterseq_)
      + sizeof(CS_CreateMonsterCheatPacket::_impl_.monsterseq_)
      - PROTOBUF_FIELD_OFFSET(CS_CreateMonsterCheatPacket, _impl_.mapid_)>(
          reinterpret_cast<char*>(&_impl_.mapid_),
          reinterpret_cast<char*>(&other->_impl_.mapid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CS_CreateMonsterCheatPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Cheat_2eproto_getter, &descriptor_table_Cheat_2eproto_once,
      file_level_metadata_Cheat_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::CS_CreateItemCheatPacket*
Arena::CreateMaybeMessage< ::Protocol::CS_CreateItemCheatPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::CS_CreateItemCheatPacket >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::CS_CreateSkillCheatPacket*
Arena::CreateMaybeMessage< ::Protocol::CS_CreateSkillCheatPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::CS_CreateSkillCheatPacket >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::CS_CreateMonsterCheatPacket*
Arena::CreateMaybeMessage< ::Protocol::CS_CreateMonsterCheatPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::CS_CreateMonsterCheatPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
