// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Drop.proto

#include "Drop.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR DropRequest::DropRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.objectid_)*/int64_t{0}
  , /*decltype(_impl_.monsterid_)*/int64_t{0}
  , /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DropRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DropRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DropRequestDefaultTypeInternal() {}
  union {
    DropRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DropRequestDefaultTypeInternal _DropRequest_default_instance_;
PROTOBUF_CONSTEXPR AddItemRequest::AddItemRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.objectid_)*/int64_t{0}
  , /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_.userseq_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AddItemRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddItemRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddItemRequestDefaultTypeInternal() {}
  union {
    AddItemRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddItemRequestDefaultTypeInternal _AddItemRequest_default_instance_;
PROTOBUF_CONSTEXPR ExpIncreaseRequest::ExpIncreaseRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.exp_)*/0
  , /*decltype(_impl_.userseq_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ExpIncreaseRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExpIncreaseRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExpIncreaseRequestDefaultTypeInternal() {}
  union {
    ExpIncreaseRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExpIncreaseRequestDefaultTypeInternal _ExpIncreaseRequest_default_instance_;
PROTOBUF_CONSTEXPR ExpIncreaseResponse::ExpIncreaseResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.exp_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ExpIncreaseResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExpIncreaseResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExpIncreaseResponseDefaultTypeInternal() {}
  union {
    ExpIncreaseResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExpIncreaseResponseDefaultTypeInternal _ExpIncreaseResponse_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Drop_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Drop_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Drop_2eproto = nullptr;

const uint32_t TableStruct_Drop_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::DropRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::DropRequest, _impl_.objectid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::DropRequest, _impl_.value_),
  PROTOBUF_FIELD_OFFSET(::Protocol::DropRequest, _impl_.monsterid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::AddItemRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::AddItemRequest, _impl_.objectid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::AddItemRequest, _impl_.value_),
  PROTOBUF_FIELD_OFFSET(::Protocol::AddItemRequest, _impl_.userseq_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::ExpIncreaseRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::ExpIncreaseRequest, _impl_.exp_),
  PROTOBUF_FIELD_OFFSET(::Protocol::ExpIncreaseRequest, _impl_.userseq_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::ExpIncreaseResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::ExpIncreaseResponse, _impl_.exp_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::DropRequest)},
  { 9, -1, -1, sizeof(::Protocol::AddItemRequest)},
  { 18, -1, -1, sizeof(::Protocol::ExpIncreaseRequest)},
  { 26, -1, -1, sizeof(::Protocol::ExpIncreaseResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_DropRequest_default_instance_._instance,
  &::Protocol::_AddItemRequest_default_instance_._instance,
  &::Protocol::_ExpIncreaseRequest_default_instance_._instance,
  &::Protocol::_ExpIncreaseResponse_default_instance_._instance,
};

const char descriptor_table_protodef_Drop_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nDrop.proto\022\010Protocol\"A\n\013DropRequest\022\020\n"
  "\010objectId\030\001 \001(\003\022\r\n\005value\030\002 \001(\005\022\021\n\tmonste"
  "rId\030\003 \001(\003\"B\n\016AddItemRequest\022\020\n\010objectId\030"
  "\001 \001(\003\022\r\n\005value\030\002 \001(\005\022\017\n\007userSeq\030\003 \001(\005\"2\n"
  "\022ExpIncreaseRequest\022\013\n\003exp\030\001 \001(\005\022\017\n\007user"
  "Seq\030\002 \001(\005\"\"\n\023ExpIncreaseResponse\022\013\n\003exp\030"
  "\001 \001(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Drop_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Drop_2eproto = {
    false, false, 253, descriptor_table_protodef_Drop_2eproto,
    "Drop.proto",
    &descriptor_table_Drop_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_Drop_2eproto::offsets,
    file_level_metadata_Drop_2eproto, file_level_enum_descriptors_Drop_2eproto,
    file_level_service_descriptors_Drop_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Drop_2eproto_getter() {
  return &descriptor_table_Drop_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Drop_2eproto(&descriptor_table_Drop_2eproto);
namespace Protocol {

// ===================================================================

class DropRequest::_Internal {
 public:
};

DropRequest::DropRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.DropRequest)
}
DropRequest::DropRequest(const DropRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DropRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.objectid_){}
    , decltype(_impl_.monsterid_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.objectid_, &from._impl_.objectid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.value_) -
    reinterpret_cast<char*>(&_impl_.objectid_)) + sizeof(_impl_.value_));
  // @@protoc_insertion_point(copy_constructor:Protocol.DropRequest)
}

inline void DropRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.objectid_){int64_t{0}}
    , decltype(_impl_.monsterid_){int64_t{0}}
    , decltype(_impl_.value_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DropRequest::~DropRequest() {
  // @@protoc_insertion_point(destructor:Protocol.DropRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DropRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DropRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DropRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.DropRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.objectid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.value_) -
      reinterpret_cast<char*>(&_impl_.objectid_)) + sizeof(_impl_.value_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DropRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 objectId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.objectid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 monsterId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.monsterid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DropRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.DropRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 objectId = 1;
  if (this->_internal_objectid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_objectid(), target);
  }

  // int32 value = 2;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_value(), target);
  }

  // int64 monsterId = 3;
  if (this->_internal_monsterid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_monsterid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.DropRequest)
  return target;
}

size_t DropRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.DropRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 objectId = 1;
  if (this->_internal_objectid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_objectid());
  }

  // int64 monsterId = 3;
  if (this->_internal_monsterid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_monsterid());
  }

  // int32 value = 2;
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DropRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DropRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DropRequest::GetClassData() const { return &_class_data_; }


void DropRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DropRequest*>(&to_msg);
  auto& from = static_cast<const DropRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.DropRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_objectid() != 0) {
    _this->_internal_set_objectid(from._internal_objectid());
  }
  if (from._internal_monsterid() != 0) {
    _this->_internal_set_monsterid(from._internal_monsterid());
  }
  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DropRequest::CopyFrom(const DropRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.DropRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DropRequest::IsInitialized() const {
  return true;
}

void DropRequest::InternalSwap(DropRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DropRequest, _impl_.value_)
      + sizeof(DropRequest::_impl_.value_)
      - PROTOBUF_FIELD_OFFSET(DropRequest, _impl_.objectid_)>(
          reinterpret_cast<char*>(&_impl_.objectid_),
          reinterpret_cast<char*>(&other->_impl_.objectid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DropRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Drop_2eproto_getter, &descriptor_table_Drop_2eproto_once,
      file_level_metadata_Drop_2eproto[0]);
}

// ===================================================================

class AddItemRequest::_Internal {
 public:
};

AddItemRequest::AddItemRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.AddItemRequest)
}
AddItemRequest::AddItemRequest(const AddItemRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AddItemRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.objectid_){}
    , decltype(_impl_.value_){}
    , decltype(_impl_.userseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.objectid_, &from._impl_.objectid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.userseq_) -
    reinterpret_cast<char*>(&_impl_.objectid_)) + sizeof(_impl_.userseq_));
  // @@protoc_insertion_point(copy_constructor:Protocol.AddItemRequest)
}

inline void AddItemRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.objectid_){int64_t{0}}
    , decltype(_impl_.value_){0}
    , decltype(_impl_.userseq_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AddItemRequest::~AddItemRequest() {
  // @@protoc_insertion_point(destructor:Protocol.AddItemRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AddItemRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AddItemRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AddItemRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.AddItemRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.objectid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.userseq_) -
      reinterpret_cast<char*>(&_impl_.objectid_)) + sizeof(_impl_.userseq_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddItemRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 objectId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.objectid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 userSeq = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AddItemRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.AddItemRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 objectId = 1;
  if (this->_internal_objectid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_objectid(), target);
  }

  // int32 value = 2;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_value(), target);
  }

  // int32 userSeq = 3;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_userseq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.AddItemRequest)
  return target;
}

size_t AddItemRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.AddItemRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 objectId = 1;
  if (this->_internal_objectid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_objectid());
  }

  // int32 value = 2;
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_value());
  }

  // int32 userSeq = 3;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_userseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AddItemRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AddItemRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AddItemRequest::GetClassData() const { return &_class_data_; }


void AddItemRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AddItemRequest*>(&to_msg);
  auto& from = static_cast<const AddItemRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.AddItemRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_objectid() != 0) {
    _this->_internal_set_objectid(from._internal_objectid());
  }
  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AddItemRequest::CopyFrom(const AddItemRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.AddItemRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddItemRequest::IsInitialized() const {
  return true;
}

void AddItemRequest::InternalSwap(AddItemRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AddItemRequest, _impl_.userseq_)
      + sizeof(AddItemRequest::_impl_.userseq_)
      - PROTOBUF_FIELD_OFFSET(AddItemRequest, _impl_.objectid_)>(
          reinterpret_cast<char*>(&_impl_.objectid_),
          reinterpret_cast<char*>(&other->_impl_.objectid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AddItemRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Drop_2eproto_getter, &descriptor_table_Drop_2eproto_once,
      file_level_metadata_Drop_2eproto[1]);
}

// ===================================================================

class ExpIncreaseRequest::_Internal {
 public:
};

ExpIncreaseRequest::ExpIncreaseRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.ExpIncreaseRequest)
}
ExpIncreaseRequest::ExpIncreaseRequest(const ExpIncreaseRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ExpIncreaseRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.exp_){}
    , decltype(_impl_.userseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.exp_, &from._impl_.exp_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.userseq_) -
    reinterpret_cast<char*>(&_impl_.exp_)) + sizeof(_impl_.userseq_));
  // @@protoc_insertion_point(copy_constructor:Protocol.ExpIncreaseRequest)
}

inline void ExpIncreaseRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.exp_){0}
    , decltype(_impl_.userseq_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ExpIncreaseRequest::~ExpIncreaseRequest() {
  // @@protoc_insertion_point(destructor:Protocol.ExpIncreaseRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ExpIncreaseRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ExpIncreaseRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ExpIncreaseRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.ExpIncreaseRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.exp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.userseq_) -
      reinterpret_cast<char*>(&_impl_.exp_)) + sizeof(_impl_.userseq_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ExpIncreaseRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 exp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.exp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 userSeq = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ExpIncreaseRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.ExpIncreaseRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 exp = 1;
  if (this->_internal_exp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_exp(), target);
  }

  // int32 userSeq = 2;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_userseq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.ExpIncreaseRequest)
  return target;
}

size_t ExpIncreaseRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.ExpIncreaseRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 exp = 1;
  if (this->_internal_exp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_exp());
  }

  // int32 userSeq = 2;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_userseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ExpIncreaseRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ExpIncreaseRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ExpIncreaseRequest::GetClassData() const { return &_class_data_; }


void ExpIncreaseRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ExpIncreaseRequest*>(&to_msg);
  auto& from = static_cast<const ExpIncreaseRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.ExpIncreaseRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_exp() != 0) {
    _this->_internal_set_exp(from._internal_exp());
  }
  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ExpIncreaseRequest::CopyFrom(const ExpIncreaseRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.ExpIncreaseRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExpIncreaseRequest::IsInitialized() const {
  return true;
}

void ExpIncreaseRequest::InternalSwap(ExpIncreaseRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExpIncreaseRequest, _impl_.userseq_)
      + sizeof(ExpIncreaseRequest::_impl_.userseq_)
      - PROTOBUF_FIELD_OFFSET(ExpIncreaseRequest, _impl_.exp_)>(
          reinterpret_cast<char*>(&_impl_.exp_),
          reinterpret_cast<char*>(&other->_impl_.exp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ExpIncreaseRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Drop_2eproto_getter, &descriptor_table_Drop_2eproto_once,
      file_level_metadata_Drop_2eproto[2]);
}

// ===================================================================

class ExpIncreaseResponse::_Internal {
 public:
};

ExpIncreaseResponse::ExpIncreaseResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.ExpIncreaseResponse)
}
ExpIncreaseResponse::ExpIncreaseResponse(const ExpIncreaseResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ExpIncreaseResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.exp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.exp_ = from._impl_.exp_;
  // @@protoc_insertion_point(copy_constructor:Protocol.ExpIncreaseResponse)
}

inline void ExpIncreaseResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.exp_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ExpIncreaseResponse::~ExpIncreaseResponse() {
  // @@protoc_insertion_point(destructor:Protocol.ExpIncreaseResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ExpIncreaseResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ExpIncreaseResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ExpIncreaseResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.ExpIncreaseResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.exp_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ExpIncreaseResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 exp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.exp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ExpIncreaseResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.ExpIncreaseResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 exp = 1;
  if (this->_internal_exp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_exp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.ExpIncreaseResponse)
  return target;
}

size_t ExpIncreaseResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.ExpIncreaseResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 exp = 1;
  if (this->_internal_exp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_exp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ExpIncreaseResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ExpIncreaseResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ExpIncreaseResponse::GetClassData() const { return &_class_data_; }


void ExpIncreaseResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ExpIncreaseResponse*>(&to_msg);
  auto& from = static_cast<const ExpIncreaseResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.ExpIncreaseResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_exp() != 0) {
    _this->_internal_set_exp(from._internal_exp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ExpIncreaseResponse::CopyFrom(const ExpIncreaseResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.ExpIncreaseResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExpIncreaseResponse::IsInitialized() const {
  return true;
}

void ExpIncreaseResponse::InternalSwap(ExpIncreaseResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.exp_, other->_impl_.exp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ExpIncreaseResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Drop_2eproto_getter, &descriptor_table_Drop_2eproto_once,
      file_level_metadata_Drop_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::DropRequest*
Arena::CreateMaybeMessage< ::Protocol::DropRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::DropRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::AddItemRequest*
Arena::CreateMaybeMessage< ::Protocol::AddItemRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::AddItemRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::ExpIncreaseRequest*
Arena::CreateMaybeMessage< ::Protocol::ExpIncreaseRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::ExpIncreaseRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::ExpIncreaseResponse*
Arena::CreateMaybeMessage< ::Protocol::ExpIncreaseResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::ExpIncreaseResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
