// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enhance.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enhance_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enhance_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enhance_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enhance_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enhance_2eproto;
namespace Protocol {
class CS_EnhanceRequest;
struct CS_EnhanceRequestDefaultTypeInternal;
extern CS_EnhanceRequestDefaultTypeInternal _CS_EnhanceRequest_default_instance_;
class SC_EnhanceFailureResponse;
struct SC_EnhanceFailureResponseDefaultTypeInternal;
extern SC_EnhanceFailureResponseDefaultTypeInternal _SC_EnhanceFailureResponse_default_instance_;
class SC_EnhanceSuccessResponse;
struct SC_EnhanceSuccessResponseDefaultTypeInternal;
extern SC_EnhanceSuccessResponseDefaultTypeInternal _SC_EnhanceSuccessResponse_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::CS_EnhanceRequest* Arena::CreateMaybeMessage<::Protocol::CS_EnhanceRequest>(Arena*);
template<> ::Protocol::SC_EnhanceFailureResponse* Arena::CreateMaybeMessage<::Protocol::SC_EnhanceFailureResponse>(Arena*);
template<> ::Protocol::SC_EnhanceSuccessResponse* Arena::CreateMaybeMessage<::Protocol::SC_EnhanceSuccessResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class CS_EnhanceRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_EnhanceRequest) */ {
 public:
  inline CS_EnhanceRequest() : CS_EnhanceRequest(nullptr) {}
  ~CS_EnhanceRequest() override;
  explicit PROTOBUF_CONSTEXPR CS_EnhanceRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_EnhanceRequest(const CS_EnhanceRequest& from);
  CS_EnhanceRequest(CS_EnhanceRequest&& from) noexcept
    : CS_EnhanceRequest() {
    *this = ::std::move(from);
  }

  inline CS_EnhanceRequest& operator=(const CS_EnhanceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_EnhanceRequest& operator=(CS_EnhanceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_EnhanceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_EnhanceRequest* internal_default_instance() {
    return reinterpret_cast<const CS_EnhanceRequest*>(
               &_CS_EnhanceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CS_EnhanceRequest& a, CS_EnhanceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_EnhanceRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_EnhanceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_EnhanceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_EnhanceRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_EnhanceRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_EnhanceRequest& from) {
    CS_EnhanceRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_EnhanceRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_EnhanceRequest";
  }
  protected:
  explicit CS_EnhanceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemIdFieldNumber = 1,
    kUserSeqFieldNumber = 2,
    kAddItemSeqFieldNumber = 3,
    kAddItemQuantityFieldNumber = 4,
  };
  // int64 itemId = 1;
  void clear_itemid();
  int64_t itemid() const;
  void set_itemid(int64_t value);
  private:
  int64_t _internal_itemid() const;
  void _internal_set_itemid(int64_t value);
  public:

  // int32 userSeq = 2;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // int32 addItemSeq = 3;
  void clear_additemseq();
  int32_t additemseq() const;
  void set_additemseq(int32_t value);
  private:
  int32_t _internal_additemseq() const;
  void _internal_set_additemseq(int32_t value);
  public:

  // int32 addItemQuantity = 4;
  void clear_additemquantity();
  int32_t additemquantity() const;
  void set_additemquantity(int32_t value);
  private:
  int32_t _internal_additemquantity() const;
  void _internal_set_additemquantity(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_EnhanceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t itemid_;
    int32_t userseq_;
    int32_t additemseq_;
    int32_t additemquantity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Enhance_2eproto;
};
// -------------------------------------------------------------------

class SC_EnhanceSuccessResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_EnhanceSuccessResponse) */ {
 public:
  inline SC_EnhanceSuccessResponse() : SC_EnhanceSuccessResponse(nullptr) {}
  ~SC_EnhanceSuccessResponse() override;
  explicit PROTOBUF_CONSTEXPR SC_EnhanceSuccessResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_EnhanceSuccessResponse(const SC_EnhanceSuccessResponse& from);
  SC_EnhanceSuccessResponse(SC_EnhanceSuccessResponse&& from) noexcept
    : SC_EnhanceSuccessResponse() {
    *this = ::std::move(from);
  }

  inline SC_EnhanceSuccessResponse& operator=(const SC_EnhanceSuccessResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_EnhanceSuccessResponse& operator=(SC_EnhanceSuccessResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_EnhanceSuccessResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_EnhanceSuccessResponse* internal_default_instance() {
    return reinterpret_cast<const SC_EnhanceSuccessResponse*>(
               &_SC_EnhanceSuccessResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SC_EnhanceSuccessResponse& a, SC_EnhanceSuccessResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_EnhanceSuccessResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_EnhanceSuccessResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_EnhanceSuccessResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_EnhanceSuccessResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_EnhanceSuccessResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_EnhanceSuccessResponse& from) {
    SC_EnhanceSuccessResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_EnhanceSuccessResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_EnhanceSuccessResponse";
  }
  protected:
  explicit SC_EnhanceSuccessResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserSeqFieldNumber = 1,
  };
  // int32 userSeq = 1;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_EnhanceSuccessResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Enhance_2eproto;
};
// -------------------------------------------------------------------

class SC_EnhanceFailureResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_EnhanceFailureResponse) */ {
 public:
  inline SC_EnhanceFailureResponse() : SC_EnhanceFailureResponse(nullptr) {}
  ~SC_EnhanceFailureResponse() override;
  explicit PROTOBUF_CONSTEXPR SC_EnhanceFailureResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_EnhanceFailureResponse(const SC_EnhanceFailureResponse& from);
  SC_EnhanceFailureResponse(SC_EnhanceFailureResponse&& from) noexcept
    : SC_EnhanceFailureResponse() {
    *this = ::std::move(from);
  }

  inline SC_EnhanceFailureResponse& operator=(const SC_EnhanceFailureResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_EnhanceFailureResponse& operator=(SC_EnhanceFailureResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_EnhanceFailureResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_EnhanceFailureResponse* internal_default_instance() {
    return reinterpret_cast<const SC_EnhanceFailureResponse*>(
               &_SC_EnhanceFailureResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SC_EnhanceFailureResponse& a, SC_EnhanceFailureResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_EnhanceFailureResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_EnhanceFailureResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_EnhanceFailureResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_EnhanceFailureResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_EnhanceFailureResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_EnhanceFailureResponse& from) {
    SC_EnhanceFailureResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_EnhanceFailureResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_EnhanceFailureResponse";
  }
  protected:
  explicit SC_EnhanceFailureResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserSeqFieldNumber = 1,
  };
  // int32 userSeq = 1;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_EnhanceFailureResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Enhance_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CS_EnhanceRequest

// int64 itemId = 1;
inline void CS_EnhanceRequest::clear_itemid() {
  _impl_.itemid_ = int64_t{0};
}
inline int64_t CS_EnhanceRequest::_internal_itemid() const {
  return _impl_.itemid_;
}
inline int64_t CS_EnhanceRequest::itemid() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_EnhanceRequest.itemId)
  return _internal_itemid();
}
inline void CS_EnhanceRequest::_internal_set_itemid(int64_t value) {
  
  _impl_.itemid_ = value;
}
inline void CS_EnhanceRequest::set_itemid(int64_t value) {
  _internal_set_itemid(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_EnhanceRequest.itemId)
}

// int32 userSeq = 2;
inline void CS_EnhanceRequest::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t CS_EnhanceRequest::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t CS_EnhanceRequest::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_EnhanceRequest.userSeq)
  return _internal_userseq();
}
inline void CS_EnhanceRequest::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void CS_EnhanceRequest::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_EnhanceRequest.userSeq)
}

// int32 addItemSeq = 3;
inline void CS_EnhanceRequest::clear_additemseq() {
  _impl_.additemseq_ = 0;
}
inline int32_t CS_EnhanceRequest::_internal_additemseq() const {
  return _impl_.additemseq_;
}
inline int32_t CS_EnhanceRequest::additemseq() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_EnhanceRequest.addItemSeq)
  return _internal_additemseq();
}
inline void CS_EnhanceRequest::_internal_set_additemseq(int32_t value) {
  
  _impl_.additemseq_ = value;
}
inline void CS_EnhanceRequest::set_additemseq(int32_t value) {
  _internal_set_additemseq(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_EnhanceRequest.addItemSeq)
}

// int32 addItemQuantity = 4;
inline void CS_EnhanceRequest::clear_additemquantity() {
  _impl_.additemquantity_ = 0;
}
inline int32_t CS_EnhanceRequest::_internal_additemquantity() const {
  return _impl_.additemquantity_;
}
inline int32_t CS_EnhanceRequest::additemquantity() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_EnhanceRequest.addItemQuantity)
  return _internal_additemquantity();
}
inline void CS_EnhanceRequest::_internal_set_additemquantity(int32_t value) {
  
  _impl_.additemquantity_ = value;
}
inline void CS_EnhanceRequest::set_additemquantity(int32_t value) {
  _internal_set_additemquantity(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_EnhanceRequest.addItemQuantity)
}

// -------------------------------------------------------------------

// SC_EnhanceSuccessResponse

// int32 userSeq = 1;
inline void SC_EnhanceSuccessResponse::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t SC_EnhanceSuccessResponse::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t SC_EnhanceSuccessResponse::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_EnhanceSuccessResponse.userSeq)
  return _internal_userseq();
}
inline void SC_EnhanceSuccessResponse::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void SC_EnhanceSuccessResponse::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_EnhanceSuccessResponse.userSeq)
}

// -------------------------------------------------------------------

// SC_EnhanceFailureResponse

// int32 userSeq = 1;
inline void SC_EnhanceFailureResponse::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t SC_EnhanceFailureResponse::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t SC_EnhanceFailureResponse::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_EnhanceFailureResponse.userSeq)
  return _internal_userseq();
}
inline void SC_EnhanceFailureResponse::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void SC_EnhanceFailureResponse::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_EnhanceFailureResponse.userSeq)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enhance_2eproto
