// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Good.proto

#include "Good.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR CS_UserGoodRequest::CS_UserGoodRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.userseq_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CS_UserGoodRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_UserGoodRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_UserGoodRequestDefaultTypeInternal() {}
  union {
    CS_UserGoodRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_UserGoodRequestDefaultTypeInternal _CS_UserGoodRequest_default_instance_;
PROTOBUF_CONSTEXPR CS_PlayerGoodRequest::CS_PlayerGoodRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.userseq_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CS_PlayerGoodRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_PlayerGoodRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_PlayerGoodRequestDefaultTypeInternal() {}
  union {
    CS_PlayerGoodRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_PlayerGoodRequestDefaultTypeInternal _CS_PlayerGoodRequest_default_instance_;
PROTOBUF_CONSTEXPR SC_UserGoodResponse::SC_UserGoodResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.usergood_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SC_UserGoodResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_UserGoodResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_UserGoodResponseDefaultTypeInternal() {}
  union {
    SC_UserGoodResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_UserGoodResponseDefaultTypeInternal _SC_UserGoodResponse_default_instance_;
PROTOBUF_CONSTEXPR SC_PlayerGoodResponse::SC_PlayerGoodResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.playergood_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SC_PlayerGoodResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_PlayerGoodResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_PlayerGoodResponseDefaultTypeInternal() {}
  union {
    SC_PlayerGoodResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_PlayerGoodResponseDefaultTypeInternal _SC_PlayerGoodResponse_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Good_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Good_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Good_2eproto = nullptr;

const uint32_t TableStruct_Good_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_UserGoodRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_UserGoodRequest, _impl_.userseq_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_PlayerGoodRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_PlayerGoodRequest, _impl_.userseq_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::SC_UserGoodResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::SC_UserGoodResponse, _impl_.usergood_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::SC_PlayerGoodResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::SC_PlayerGoodResponse, _impl_.playergood_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::CS_UserGoodRequest)},
  { 7, -1, -1, sizeof(::Protocol::CS_PlayerGoodRequest)},
  { 14, -1, -1, sizeof(::Protocol::SC_UserGoodResponse)},
  { 21, -1, -1, sizeof(::Protocol::SC_PlayerGoodResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_CS_UserGoodRequest_default_instance_._instance,
  &::Protocol::_CS_PlayerGoodRequest_default_instance_._instance,
  &::Protocol::_SC_UserGoodResponse_default_instance_._instance,
  &::Protocol::_SC_PlayerGoodResponse_default_instance_._instance,
};

const char descriptor_table_protodef_Good_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nGood.proto\022\010Protocol\032\014User_2.proto\032\016Pl"
  "ayer_2.proto\"%\n\022CS_UserGoodRequest\022\017\n\007us"
  "erSeq\030\001 \001(\005\"\'\n\024CS_PlayerGoodRequest\022\017\n\007u"
  "serSeq\030\001 \001(\005\";\n\023SC_UserGoodResponse\022$\n\010u"
  "serGood\030\001 \001(\0132\022.Protocol.UserGood\"A\n\025SC_"
  "PlayerGoodResponse\022(\n\nplayerGood\030\002 \001(\0132\024"
  ".Protocol.PlayerGoodb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Good_2eproto_deps[2] = {
  &::descriptor_table_Player_5f2_2eproto,
  &::descriptor_table_User_5f2_2eproto,
};
static ::_pbi::once_flag descriptor_table_Good_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Good_2eproto = {
    false, false, 268, descriptor_table_protodef_Good_2eproto,
    "Good.proto",
    &descriptor_table_Good_2eproto_once, descriptor_table_Good_2eproto_deps, 2, 4,
    schemas, file_default_instances, TableStruct_Good_2eproto::offsets,
    file_level_metadata_Good_2eproto, file_level_enum_descriptors_Good_2eproto,
    file_level_service_descriptors_Good_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Good_2eproto_getter() {
  return &descriptor_table_Good_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Good_2eproto(&descriptor_table_Good_2eproto);
namespace Protocol {

// ===================================================================

class CS_UserGoodRequest::_Internal {
 public:
};

CS_UserGoodRequest::CS_UserGoodRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_UserGoodRequest)
}
CS_UserGoodRequest::CS_UserGoodRequest(const CS_UserGoodRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CS_UserGoodRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.userseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.userseq_ = from._impl_.userseq_;
  // @@protoc_insertion_point(copy_constructor:Protocol.CS_UserGoodRequest)
}

inline void CS_UserGoodRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.userseq_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CS_UserGoodRequest::~CS_UserGoodRequest() {
  // @@protoc_insertion_point(destructor:Protocol.CS_UserGoodRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CS_UserGoodRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CS_UserGoodRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CS_UserGoodRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_UserGoodRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userseq_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CS_UserGoodRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 userSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CS_UserGoodRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_UserGoodRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_userseq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_UserGoodRequest)
  return target;
}

size_t CS_UserGoodRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CS_UserGoodRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_userseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CS_UserGoodRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CS_UserGoodRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CS_UserGoodRequest::GetClassData() const { return &_class_data_; }


void CS_UserGoodRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CS_UserGoodRequest*>(&to_msg);
  auto& from = static_cast<const CS_UserGoodRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_UserGoodRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CS_UserGoodRequest::CopyFrom(const CS_UserGoodRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_UserGoodRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_UserGoodRequest::IsInitialized() const {
  return true;
}

void CS_UserGoodRequest::InternalSwap(CS_UserGoodRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.userseq_, other->_impl_.userseq_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CS_UserGoodRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Good_2eproto_getter, &descriptor_table_Good_2eproto_once,
      file_level_metadata_Good_2eproto[0]);
}

// ===================================================================

class CS_PlayerGoodRequest::_Internal {
 public:
};

CS_PlayerGoodRequest::CS_PlayerGoodRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_PlayerGoodRequest)
}
CS_PlayerGoodRequest::CS_PlayerGoodRequest(const CS_PlayerGoodRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CS_PlayerGoodRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.userseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.userseq_ = from._impl_.userseq_;
  // @@protoc_insertion_point(copy_constructor:Protocol.CS_PlayerGoodRequest)
}

inline void CS_PlayerGoodRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.userseq_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CS_PlayerGoodRequest::~CS_PlayerGoodRequest() {
  // @@protoc_insertion_point(destructor:Protocol.CS_PlayerGoodRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CS_PlayerGoodRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CS_PlayerGoodRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CS_PlayerGoodRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_PlayerGoodRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userseq_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CS_PlayerGoodRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 userSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CS_PlayerGoodRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_PlayerGoodRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_userseq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_PlayerGoodRequest)
  return target;
}

size_t CS_PlayerGoodRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CS_PlayerGoodRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_userseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CS_PlayerGoodRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CS_PlayerGoodRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CS_PlayerGoodRequest::GetClassData() const { return &_class_data_; }


void CS_PlayerGoodRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CS_PlayerGoodRequest*>(&to_msg);
  auto& from = static_cast<const CS_PlayerGoodRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_PlayerGoodRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CS_PlayerGoodRequest::CopyFrom(const CS_PlayerGoodRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_PlayerGoodRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_PlayerGoodRequest::IsInitialized() const {
  return true;
}

void CS_PlayerGoodRequest::InternalSwap(CS_PlayerGoodRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.userseq_, other->_impl_.userseq_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CS_PlayerGoodRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Good_2eproto_getter, &descriptor_table_Good_2eproto_once,
      file_level_metadata_Good_2eproto[1]);
}

// ===================================================================

class SC_UserGoodResponse::_Internal {
 public:
  static const ::Protocol::UserGood& usergood(const SC_UserGoodResponse* msg);
};

const ::Protocol::UserGood&
SC_UserGoodResponse::_Internal::usergood(const SC_UserGoodResponse* msg) {
  return *msg->_impl_.usergood_;
}
void SC_UserGoodResponse::clear_usergood() {
  if (GetArenaForAllocation() == nullptr && _impl_.usergood_ != nullptr) {
    delete _impl_.usergood_;
  }
  _impl_.usergood_ = nullptr;
}
SC_UserGoodResponse::SC_UserGoodResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_UserGoodResponse)
}
SC_UserGoodResponse::SC_UserGoodResponse(const SC_UserGoodResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SC_UserGoodResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.usergood_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_usergood()) {
    _this->_impl_.usergood_ = new ::Protocol::UserGood(*from._impl_.usergood_);
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.SC_UserGoodResponse)
}

inline void SC_UserGoodResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.usergood_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SC_UserGoodResponse::~SC_UserGoodResponse() {
  // @@protoc_insertion_point(destructor:Protocol.SC_UserGoodResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SC_UserGoodResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.usergood_;
}

void SC_UserGoodResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SC_UserGoodResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_UserGoodResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.usergood_ != nullptr) {
    delete _impl_.usergood_;
  }
  _impl_.usergood_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SC_UserGoodResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Protocol.UserGood userGood = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_usergood(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SC_UserGoodResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_UserGoodResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Protocol.UserGood userGood = 1;
  if (this->_internal_has_usergood()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::usergood(this),
        _Internal::usergood(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_UserGoodResponse)
  return target;
}

size_t SC_UserGoodResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.SC_UserGoodResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.UserGood userGood = 1;
  if (this->_internal_has_usergood()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.usergood_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SC_UserGoodResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SC_UserGoodResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SC_UserGoodResponse::GetClassData() const { return &_class_data_; }


void SC_UserGoodResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SC_UserGoodResponse*>(&to_msg);
  auto& from = static_cast<const SC_UserGoodResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_UserGoodResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_usergood()) {
    _this->_internal_mutable_usergood()->::Protocol::UserGood::MergeFrom(
        from._internal_usergood());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SC_UserGoodResponse::CopyFrom(const SC_UserGoodResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_UserGoodResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SC_UserGoodResponse::IsInitialized() const {
  return true;
}

void SC_UserGoodResponse::InternalSwap(SC_UserGoodResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.usergood_, other->_impl_.usergood_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SC_UserGoodResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Good_2eproto_getter, &descriptor_table_Good_2eproto_once,
      file_level_metadata_Good_2eproto[2]);
}

// ===================================================================

class SC_PlayerGoodResponse::_Internal {
 public:
  static const ::Protocol::PlayerGood& playergood(const SC_PlayerGoodResponse* msg);
};

const ::Protocol::PlayerGood&
SC_PlayerGoodResponse::_Internal::playergood(const SC_PlayerGoodResponse* msg) {
  return *msg->_impl_.playergood_;
}
void SC_PlayerGoodResponse::clear_playergood() {
  if (GetArenaForAllocation() == nullptr && _impl_.playergood_ != nullptr) {
    delete _impl_.playergood_;
  }
  _impl_.playergood_ = nullptr;
}
SC_PlayerGoodResponse::SC_PlayerGoodResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_PlayerGoodResponse)
}
SC_PlayerGoodResponse::SC_PlayerGoodResponse(const SC_PlayerGoodResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SC_PlayerGoodResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.playergood_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_playergood()) {
    _this->_impl_.playergood_ = new ::Protocol::PlayerGood(*from._impl_.playergood_);
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.SC_PlayerGoodResponse)
}

inline void SC_PlayerGoodResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.playergood_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SC_PlayerGoodResponse::~SC_PlayerGoodResponse() {
  // @@protoc_insertion_point(destructor:Protocol.SC_PlayerGoodResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SC_PlayerGoodResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.playergood_;
}

void SC_PlayerGoodResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SC_PlayerGoodResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_PlayerGoodResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.playergood_ != nullptr) {
    delete _impl_.playergood_;
  }
  _impl_.playergood_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SC_PlayerGoodResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Protocol.PlayerGood playerGood = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_playergood(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SC_PlayerGoodResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_PlayerGoodResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Protocol.PlayerGood playerGood = 2;
  if (this->_internal_has_playergood()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::playergood(this),
        _Internal::playergood(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_PlayerGoodResponse)
  return target;
}

size_t SC_PlayerGoodResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.SC_PlayerGoodResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.PlayerGood playerGood = 2;
  if (this->_internal_has_playergood()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.playergood_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SC_PlayerGoodResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SC_PlayerGoodResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SC_PlayerGoodResponse::GetClassData() const { return &_class_data_; }


void SC_PlayerGoodResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SC_PlayerGoodResponse*>(&to_msg);
  auto& from = static_cast<const SC_PlayerGoodResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_PlayerGoodResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_playergood()) {
    _this->_internal_mutable_playergood()->::Protocol::PlayerGood::MergeFrom(
        from._internal_playergood());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SC_PlayerGoodResponse::CopyFrom(const SC_PlayerGoodResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_PlayerGoodResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SC_PlayerGoodResponse::IsInitialized() const {
  return true;
}

void SC_PlayerGoodResponse::InternalSwap(SC_PlayerGoodResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.playergood_, other->_impl_.playergood_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SC_PlayerGoodResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Good_2eproto_getter, &descriptor_table_Good_2eproto_once,
      file_level_metadata_Good_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::CS_UserGoodRequest*
Arena::CreateMaybeMessage< ::Protocol::CS_UserGoodRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::CS_UserGoodRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::CS_PlayerGoodRequest*
Arena::CreateMaybeMessage< ::Protocol::CS_PlayerGoodRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::CS_PlayerGoodRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::SC_UserGoodResponse*
Arena::CreateMaybeMessage< ::Protocol::SC_UserGoodResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::SC_UserGoodResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::SC_PlayerGoodResponse*
Arena::CreateMaybeMessage< ::Protocol::SC_PlayerGoodResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::SC_PlayerGoodResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
