// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Item.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Item_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Item_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Item_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Item_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Item_2eproto;
namespace Protocol {
class CS_ChangeInventoryRequest;
struct CS_ChangeInventoryRequestDefaultTypeInternal;
extern CS_ChangeInventoryRequestDefaultTypeInternal _CS_ChangeInventoryRequest_default_instance_;
class CS_EquipChangeRequest;
struct CS_EquipChangeRequestDefaultTypeInternal;
extern CS_EquipChangeRequestDefaultTypeInternal _CS_EquipChangeRequest_default_instance_;
class CS_EquipInfoRequest;
struct CS_EquipInfoRequestDefaultTypeInternal;
extern CS_EquipInfoRequestDefaultTypeInternal _CS_EquipInfoRequest_default_instance_;
class CS_ItemQuickSlotChangeRequest;
struct CS_ItemQuickSlotChangeRequestDefaultTypeInternal;
extern CS_ItemQuickSlotChangeRequestDefaultTypeInternal _CS_ItemQuickSlotChangeRequest_default_instance_;
class CS_UnequipChangeRequest;
struct CS_UnequipChangeRequestDefaultTypeInternal;
extern CS_UnequipChangeRequestDefaultTypeInternal _CS_UnequipChangeRequest_default_instance_;
class SC_ChangeInventoryResponse;
struct SC_ChangeInventoryResponseDefaultTypeInternal;
extern SC_ChangeInventoryResponseDefaultTypeInternal _SC_ChangeInventoryResponse_default_instance_;
class SC_EquipChangeRespnse;
struct SC_EquipChangeRespnseDefaultTypeInternal;
extern SC_EquipChangeRespnseDefaultTypeInternal _SC_EquipChangeRespnse_default_instance_;
class SC_EquipInfoResponse;
struct SC_EquipInfoResponseDefaultTypeInternal;
extern SC_EquipInfoResponseDefaultTypeInternal _SC_EquipInfoResponse_default_instance_;
class SC_ItemQuickSlotChangeResponse;
struct SC_ItemQuickSlotChangeResponseDefaultTypeInternal;
extern SC_ItemQuickSlotChangeResponseDefaultTypeInternal _SC_ItemQuickSlotChangeResponse_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::CS_ChangeInventoryRequest* Arena::CreateMaybeMessage<::Protocol::CS_ChangeInventoryRequest>(Arena*);
template<> ::Protocol::CS_EquipChangeRequest* Arena::CreateMaybeMessage<::Protocol::CS_EquipChangeRequest>(Arena*);
template<> ::Protocol::CS_EquipInfoRequest* Arena::CreateMaybeMessage<::Protocol::CS_EquipInfoRequest>(Arena*);
template<> ::Protocol::CS_ItemQuickSlotChangeRequest* Arena::CreateMaybeMessage<::Protocol::CS_ItemQuickSlotChangeRequest>(Arena*);
template<> ::Protocol::CS_UnequipChangeRequest* Arena::CreateMaybeMessage<::Protocol::CS_UnequipChangeRequest>(Arena*);
template<> ::Protocol::SC_ChangeInventoryResponse* Arena::CreateMaybeMessage<::Protocol::SC_ChangeInventoryResponse>(Arena*);
template<> ::Protocol::SC_EquipChangeRespnse* Arena::CreateMaybeMessage<::Protocol::SC_EquipChangeRespnse>(Arena*);
template<> ::Protocol::SC_EquipInfoResponse* Arena::CreateMaybeMessage<::Protocol::SC_EquipInfoResponse>(Arena*);
template<> ::Protocol::SC_ItemQuickSlotChangeResponse* Arena::CreateMaybeMessage<::Protocol::SC_ItemQuickSlotChangeResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class CS_EquipInfoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_EquipInfoRequest) */ {
 public:
  inline CS_EquipInfoRequest() : CS_EquipInfoRequest(nullptr) {}
  ~CS_EquipInfoRequest() override;
  explicit PROTOBUF_CONSTEXPR CS_EquipInfoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_EquipInfoRequest(const CS_EquipInfoRequest& from);
  CS_EquipInfoRequest(CS_EquipInfoRequest&& from) noexcept
    : CS_EquipInfoRequest() {
    *this = ::std::move(from);
  }

  inline CS_EquipInfoRequest& operator=(const CS_EquipInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_EquipInfoRequest& operator=(CS_EquipInfoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_EquipInfoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_EquipInfoRequest* internal_default_instance() {
    return reinterpret_cast<const CS_EquipInfoRequest*>(
               &_CS_EquipInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CS_EquipInfoRequest& a, CS_EquipInfoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_EquipInfoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_EquipInfoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_EquipInfoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_EquipInfoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_EquipInfoRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_EquipInfoRequest& from) {
    CS_EquipInfoRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_EquipInfoRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_EquipInfoRequest";
  }
  protected:
  explicit CS_EquipInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserSeqFieldNumber = 1,
  };
  // int32 userSeq = 1;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_EquipInfoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class SC_EquipInfoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_EquipInfoResponse) */ {
 public:
  inline SC_EquipInfoResponse() : SC_EquipInfoResponse(nullptr) {}
  ~SC_EquipInfoResponse() override;
  explicit PROTOBUF_CONSTEXPR SC_EquipInfoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_EquipInfoResponse(const SC_EquipInfoResponse& from);
  SC_EquipInfoResponse(SC_EquipInfoResponse&& from) noexcept
    : SC_EquipInfoResponse() {
    *this = ::std::move(from);
  }

  inline SC_EquipInfoResponse& operator=(const SC_EquipInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_EquipInfoResponse& operator=(SC_EquipInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_EquipInfoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_EquipInfoResponse* internal_default_instance() {
    return reinterpret_cast<const SC_EquipInfoResponse*>(
               &_SC_EquipInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SC_EquipInfoResponse& a, SC_EquipInfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_EquipInfoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_EquipInfoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_EquipInfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_EquipInfoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_EquipInfoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_EquipInfoResponse& from) {
    SC_EquipInfoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_EquipInfoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_EquipInfoResponse";
  }
  protected:
  explicit SC_EquipInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEquipsFieldNumber = 1,
  };
  // repeated .Protocol.Equip equips = 1;
  int equips_size() const;
  private:
  int _internal_equips_size() const;
  public:
  void clear_equips();
  ::Protocol::Equip* mutable_equips(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equip >*
      mutable_equips();
  private:
  const ::Protocol::Equip& _internal_equips(int index) const;
  ::Protocol::Equip* _internal_add_equips();
  public:
  const ::Protocol::Equip& equips(int index) const;
  ::Protocol::Equip* add_equips();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equip >&
      equips() const;

  // @@protoc_insertion_point(class_scope:Protocol.SC_EquipInfoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equip > equips_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class CS_EquipChangeRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_EquipChangeRequest) */ {
 public:
  inline CS_EquipChangeRequest() : CS_EquipChangeRequest(nullptr) {}
  ~CS_EquipChangeRequest() override;
  explicit PROTOBUF_CONSTEXPR CS_EquipChangeRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_EquipChangeRequest(const CS_EquipChangeRequest& from);
  CS_EquipChangeRequest(CS_EquipChangeRequest&& from) noexcept
    : CS_EquipChangeRequest() {
    *this = ::std::move(from);
  }

  inline CS_EquipChangeRequest& operator=(const CS_EquipChangeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_EquipChangeRequest& operator=(CS_EquipChangeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_EquipChangeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_EquipChangeRequest* internal_default_instance() {
    return reinterpret_cast<const CS_EquipChangeRequest*>(
               &_CS_EquipChangeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CS_EquipChangeRequest& a, CS_EquipChangeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_EquipChangeRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_EquipChangeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_EquipChangeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_EquipChangeRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_EquipChangeRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_EquipChangeRequest& from) {
    CS_EquipChangeRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_EquipChangeRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_EquipChangeRequest";
  }
  protected:
  explicit CS_EquipChangeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectIdFieldNumber = 1,
    kUserSeqFieldNumber = 2,
  };
  // int64 objectId = 1;
  void clear_objectid();
  int64_t objectid() const;
  void set_objectid(int64_t value);
  private:
  int64_t _internal_objectid() const;
  void _internal_set_objectid(int64_t value);
  public:

  // int32 userSeq = 2;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_EquipChangeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t objectid_;
    int32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class CS_UnequipChangeRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_UnequipChangeRequest) */ {
 public:
  inline CS_UnequipChangeRequest() : CS_UnequipChangeRequest(nullptr) {}
  ~CS_UnequipChangeRequest() override;
  explicit PROTOBUF_CONSTEXPR CS_UnequipChangeRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_UnequipChangeRequest(const CS_UnequipChangeRequest& from);
  CS_UnequipChangeRequest(CS_UnequipChangeRequest&& from) noexcept
    : CS_UnequipChangeRequest() {
    *this = ::std::move(from);
  }

  inline CS_UnequipChangeRequest& operator=(const CS_UnequipChangeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_UnequipChangeRequest& operator=(CS_UnequipChangeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_UnequipChangeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_UnequipChangeRequest* internal_default_instance() {
    return reinterpret_cast<const CS_UnequipChangeRequest*>(
               &_CS_UnequipChangeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CS_UnequipChangeRequest& a, CS_UnequipChangeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_UnequipChangeRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_UnequipChangeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_UnequipChangeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_UnequipChangeRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_UnequipChangeRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_UnequipChangeRequest& from) {
    CS_UnequipChangeRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_UnequipChangeRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_UnequipChangeRequest";
  }
  protected:
  explicit CS_UnequipChangeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectIdFieldNumber = 1,
    kUserSeqFieldNumber = 2,
  };
  // int64 objectId = 1;
  void clear_objectid();
  int64_t objectid() const;
  void set_objectid(int64_t value);
  private:
  int64_t _internal_objectid() const;
  void _internal_set_objectid(int64_t value);
  public:

  // int32 userSeq = 2;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_UnequipChangeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t objectid_;
    int32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class SC_EquipChangeRespnse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_EquipChangeRespnse) */ {
 public:
  inline SC_EquipChangeRespnse() : SC_EquipChangeRespnse(nullptr) {}
  ~SC_EquipChangeRespnse() override;
  explicit PROTOBUF_CONSTEXPR SC_EquipChangeRespnse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_EquipChangeRespnse(const SC_EquipChangeRespnse& from);
  SC_EquipChangeRespnse(SC_EquipChangeRespnse&& from) noexcept
    : SC_EquipChangeRespnse() {
    *this = ::std::move(from);
  }

  inline SC_EquipChangeRespnse& operator=(const SC_EquipChangeRespnse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_EquipChangeRespnse& operator=(SC_EquipChangeRespnse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_EquipChangeRespnse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_EquipChangeRespnse* internal_default_instance() {
    return reinterpret_cast<const SC_EquipChangeRespnse*>(
               &_SC_EquipChangeRespnse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SC_EquipChangeRespnse& a, SC_EquipChangeRespnse& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_EquipChangeRespnse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_EquipChangeRespnse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_EquipChangeRespnse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_EquipChangeRespnse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_EquipChangeRespnse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_EquipChangeRespnse& from) {
    SC_EquipChangeRespnse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_EquipChangeRespnse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_EquipChangeRespnse";
  }
  protected:
  explicit SC_EquipChangeRespnse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // int32 success = 1;
  void clear_success();
  int32_t success() const;
  void set_success(int32_t value);
  private:
  int32_t _internal_success() const;
  void _internal_set_success(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_EquipChangeRespnse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class CS_ChangeInventoryRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_ChangeInventoryRequest) */ {
 public:
  inline CS_ChangeInventoryRequest() : CS_ChangeInventoryRequest(nullptr) {}
  ~CS_ChangeInventoryRequest() override;
  explicit PROTOBUF_CONSTEXPR CS_ChangeInventoryRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_ChangeInventoryRequest(const CS_ChangeInventoryRequest& from);
  CS_ChangeInventoryRequest(CS_ChangeInventoryRequest&& from) noexcept
    : CS_ChangeInventoryRequest() {
    *this = ::std::move(from);
  }

  inline CS_ChangeInventoryRequest& operator=(const CS_ChangeInventoryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_ChangeInventoryRequest& operator=(CS_ChangeInventoryRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_ChangeInventoryRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_ChangeInventoryRequest* internal_default_instance() {
    return reinterpret_cast<const CS_ChangeInventoryRequest*>(
               &_CS_ChangeInventoryRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(CS_ChangeInventoryRequest& a, CS_ChangeInventoryRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_ChangeInventoryRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_ChangeInventoryRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_ChangeInventoryRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_ChangeInventoryRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_ChangeInventoryRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_ChangeInventoryRequest& from) {
    CS_ChangeInventoryRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_ChangeInventoryRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_ChangeInventoryRequest";
  }
  protected:
  explicit CS_ChangeInventoryRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserSeqFieldNumber = 1,
    kBeforeSlotIdxFieldNumber = 2,
    kChangeSlotIdxFieldNumber = 3,
  };
  // int32 userSeq = 1;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // int32 beforeSlotIdx = 2;
  void clear_beforeslotidx();
  int32_t beforeslotidx() const;
  void set_beforeslotidx(int32_t value);
  private:
  int32_t _internal_beforeslotidx() const;
  void _internal_set_beforeslotidx(int32_t value);
  public:

  // int32 changeSlotIdx = 3;
  void clear_changeslotidx();
  int32_t changeslotidx() const;
  void set_changeslotidx(int32_t value);
  private:
  int32_t _internal_changeslotidx() const;
  void _internal_set_changeslotidx(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_ChangeInventoryRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t userseq_;
    int32_t beforeslotidx_;
    int32_t changeslotidx_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class SC_ChangeInventoryResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_ChangeInventoryResponse) */ {
 public:
  inline SC_ChangeInventoryResponse() : SC_ChangeInventoryResponse(nullptr) {}
  ~SC_ChangeInventoryResponse() override;
  explicit PROTOBUF_CONSTEXPR SC_ChangeInventoryResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_ChangeInventoryResponse(const SC_ChangeInventoryResponse& from);
  SC_ChangeInventoryResponse(SC_ChangeInventoryResponse&& from) noexcept
    : SC_ChangeInventoryResponse() {
    *this = ::std::move(from);
  }

  inline SC_ChangeInventoryResponse& operator=(const SC_ChangeInventoryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_ChangeInventoryResponse& operator=(SC_ChangeInventoryResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_ChangeInventoryResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_ChangeInventoryResponse* internal_default_instance() {
    return reinterpret_cast<const SC_ChangeInventoryResponse*>(
               &_SC_ChangeInventoryResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(SC_ChangeInventoryResponse& a, SC_ChangeInventoryResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_ChangeInventoryResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_ChangeInventoryResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_ChangeInventoryResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_ChangeInventoryResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_ChangeInventoryResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_ChangeInventoryResponse& from) {
    SC_ChangeInventoryResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_ChangeInventoryResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_ChangeInventoryResponse";
  }
  protected:
  explicit SC_ChangeInventoryResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // int32 success = 1;
  void clear_success();
  int32_t success() const;
  void set_success(int32_t value);
  private:
  int32_t _internal_success() const;
  void _internal_set_success(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_ChangeInventoryResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class CS_ItemQuickSlotChangeRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_ItemQuickSlotChangeRequest) */ {
 public:
  inline CS_ItemQuickSlotChangeRequest() : CS_ItemQuickSlotChangeRequest(nullptr) {}
  ~CS_ItemQuickSlotChangeRequest() override;
  explicit PROTOBUF_CONSTEXPR CS_ItemQuickSlotChangeRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_ItemQuickSlotChangeRequest(const CS_ItemQuickSlotChangeRequest& from);
  CS_ItemQuickSlotChangeRequest(CS_ItemQuickSlotChangeRequest&& from) noexcept
    : CS_ItemQuickSlotChangeRequest() {
    *this = ::std::move(from);
  }

  inline CS_ItemQuickSlotChangeRequest& operator=(const CS_ItemQuickSlotChangeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_ItemQuickSlotChangeRequest& operator=(CS_ItemQuickSlotChangeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_ItemQuickSlotChangeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_ItemQuickSlotChangeRequest* internal_default_instance() {
    return reinterpret_cast<const CS_ItemQuickSlotChangeRequest*>(
               &_CS_ItemQuickSlotChangeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(CS_ItemQuickSlotChangeRequest& a, CS_ItemQuickSlotChangeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_ItemQuickSlotChangeRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_ItemQuickSlotChangeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_ItemQuickSlotChangeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_ItemQuickSlotChangeRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_ItemQuickSlotChangeRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_ItemQuickSlotChangeRequest& from) {
    CS_ItemQuickSlotChangeRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_ItemQuickSlotChangeRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_ItemQuickSlotChangeRequest";
  }
  protected:
  explicit CS_ItemQuickSlotChangeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemIdFieldNumber = 2,
    kUserSeqFieldNumber = 1,
    kConIdxFieldNumber = 3,
  };
  // int64 itemId = 2;
  void clear_itemid();
  int64_t itemid() const;
  void set_itemid(int64_t value);
  private:
  int64_t _internal_itemid() const;
  void _internal_set_itemid(int64_t value);
  public:

  // int32 userSeq = 1;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // int32 conIdx = 3;
  void clear_conidx();
  int32_t conidx() const;
  void set_conidx(int32_t value);
  private:
  int32_t _internal_conidx() const;
  void _internal_set_conidx(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_ItemQuickSlotChangeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t itemid_;
    int32_t userseq_;
    int32_t conidx_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class SC_ItemQuickSlotChangeResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_ItemQuickSlotChangeResponse) */ {
 public:
  inline SC_ItemQuickSlotChangeResponse() : SC_ItemQuickSlotChangeResponse(nullptr) {}
  ~SC_ItemQuickSlotChangeResponse() override;
  explicit PROTOBUF_CONSTEXPR SC_ItemQuickSlotChangeResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_ItemQuickSlotChangeResponse(const SC_ItemQuickSlotChangeResponse& from);
  SC_ItemQuickSlotChangeResponse(SC_ItemQuickSlotChangeResponse&& from) noexcept
    : SC_ItemQuickSlotChangeResponse() {
    *this = ::std::move(from);
  }

  inline SC_ItemQuickSlotChangeResponse& operator=(const SC_ItemQuickSlotChangeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_ItemQuickSlotChangeResponse& operator=(SC_ItemQuickSlotChangeResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_ItemQuickSlotChangeResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_ItemQuickSlotChangeResponse* internal_default_instance() {
    return reinterpret_cast<const SC_ItemQuickSlotChangeResponse*>(
               &_SC_ItemQuickSlotChangeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(SC_ItemQuickSlotChangeResponse& a, SC_ItemQuickSlotChangeResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_ItemQuickSlotChangeResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_ItemQuickSlotChangeResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_ItemQuickSlotChangeResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_ItemQuickSlotChangeResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_ItemQuickSlotChangeResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_ItemQuickSlotChangeResponse& from) {
    SC_ItemQuickSlotChangeResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_ItemQuickSlotChangeResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_ItemQuickSlotChangeResponse";
  }
  protected:
  explicit SC_ItemQuickSlotChangeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // int32 success = 1;
  void clear_success();
  int32_t success() const;
  void set_success(int32_t value);
  private:
  int32_t _internal_success() const;
  void _internal_set_success(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_ItemQuickSlotChangeResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Item_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CS_EquipInfoRequest

// int32 userSeq = 1;
inline void CS_EquipInfoRequest::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t CS_EquipInfoRequest::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t CS_EquipInfoRequest::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_EquipInfoRequest.userSeq)
  return _internal_userseq();
}
inline void CS_EquipInfoRequest::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void CS_EquipInfoRequest::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_EquipInfoRequest.userSeq)
}

// -------------------------------------------------------------------

// SC_EquipInfoResponse

// repeated .Protocol.Equip equips = 1;
inline int SC_EquipInfoResponse::_internal_equips_size() const {
  return _impl_.equips_.size();
}
inline int SC_EquipInfoResponse::equips_size() const {
  return _internal_equips_size();
}
inline ::Protocol::Equip* SC_EquipInfoResponse::mutable_equips(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.SC_EquipInfoResponse.equips)
  return _impl_.equips_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equip >*
SC_EquipInfoResponse::mutable_equips() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.SC_EquipInfoResponse.equips)
  return &_impl_.equips_;
}
inline const ::Protocol::Equip& SC_EquipInfoResponse::_internal_equips(int index) const {
  return _impl_.equips_.Get(index);
}
inline const ::Protocol::Equip& SC_EquipInfoResponse::equips(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.SC_EquipInfoResponse.equips)
  return _internal_equips(index);
}
inline ::Protocol::Equip* SC_EquipInfoResponse::_internal_add_equips() {
  return _impl_.equips_.Add();
}
inline ::Protocol::Equip* SC_EquipInfoResponse::add_equips() {
  ::Protocol::Equip* _add = _internal_add_equips();
  // @@protoc_insertion_point(field_add:Protocol.SC_EquipInfoResponse.equips)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equip >&
SC_EquipInfoResponse::equips() const {
  // @@protoc_insertion_point(field_list:Protocol.SC_EquipInfoResponse.equips)
  return _impl_.equips_;
}

// -------------------------------------------------------------------

// CS_EquipChangeRequest

// int64 objectId = 1;
inline void CS_EquipChangeRequest::clear_objectid() {
  _impl_.objectid_ = int64_t{0};
}
inline int64_t CS_EquipChangeRequest::_internal_objectid() const {
  return _impl_.objectid_;
}
inline int64_t CS_EquipChangeRequest::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_EquipChangeRequest.objectId)
  return _internal_objectid();
}
inline void CS_EquipChangeRequest::_internal_set_objectid(int64_t value) {
  
  _impl_.objectid_ = value;
}
inline void CS_EquipChangeRequest::set_objectid(int64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_EquipChangeRequest.objectId)
}

// int32 userSeq = 2;
inline void CS_EquipChangeRequest::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t CS_EquipChangeRequest::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t CS_EquipChangeRequest::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_EquipChangeRequest.userSeq)
  return _internal_userseq();
}
inline void CS_EquipChangeRequest::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void CS_EquipChangeRequest::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_EquipChangeRequest.userSeq)
}

// -------------------------------------------------------------------

// CS_UnequipChangeRequest

// int64 objectId = 1;
inline void CS_UnequipChangeRequest::clear_objectid() {
  _impl_.objectid_ = int64_t{0};
}
inline int64_t CS_UnequipChangeRequest::_internal_objectid() const {
  return _impl_.objectid_;
}
inline int64_t CS_UnequipChangeRequest::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_UnequipChangeRequest.objectId)
  return _internal_objectid();
}
inline void CS_UnequipChangeRequest::_internal_set_objectid(int64_t value) {
  
  _impl_.objectid_ = value;
}
inline void CS_UnequipChangeRequest::set_objectid(int64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_UnequipChangeRequest.objectId)
}

// int32 userSeq = 2;
inline void CS_UnequipChangeRequest::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t CS_UnequipChangeRequest::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t CS_UnequipChangeRequest::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_UnequipChangeRequest.userSeq)
  return _internal_userseq();
}
inline void CS_UnequipChangeRequest::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void CS_UnequipChangeRequest::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_UnequipChangeRequest.userSeq)
}

// -------------------------------------------------------------------

// SC_EquipChangeRespnse

// int32 success = 1;
inline void SC_EquipChangeRespnse::clear_success() {
  _impl_.success_ = 0;
}
inline int32_t SC_EquipChangeRespnse::_internal_success() const {
  return _impl_.success_;
}
inline int32_t SC_EquipChangeRespnse::success() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_EquipChangeRespnse.success)
  return _internal_success();
}
inline void SC_EquipChangeRespnse::_internal_set_success(int32_t value) {
  
  _impl_.success_ = value;
}
inline void SC_EquipChangeRespnse::set_success(int32_t value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_EquipChangeRespnse.success)
}

// -------------------------------------------------------------------

// CS_ChangeInventoryRequest

// int32 userSeq = 1;
inline void CS_ChangeInventoryRequest::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t CS_ChangeInventoryRequest::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t CS_ChangeInventoryRequest::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_ChangeInventoryRequest.userSeq)
  return _internal_userseq();
}
inline void CS_ChangeInventoryRequest::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void CS_ChangeInventoryRequest::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_ChangeInventoryRequest.userSeq)
}

// int32 beforeSlotIdx = 2;
inline void CS_ChangeInventoryRequest::clear_beforeslotidx() {
  _impl_.beforeslotidx_ = 0;
}
inline int32_t CS_ChangeInventoryRequest::_internal_beforeslotidx() const {
  return _impl_.beforeslotidx_;
}
inline int32_t CS_ChangeInventoryRequest::beforeslotidx() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_ChangeInventoryRequest.beforeSlotIdx)
  return _internal_beforeslotidx();
}
inline void CS_ChangeInventoryRequest::_internal_set_beforeslotidx(int32_t value) {
  
  _impl_.beforeslotidx_ = value;
}
inline void CS_ChangeInventoryRequest::set_beforeslotidx(int32_t value) {
  _internal_set_beforeslotidx(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_ChangeInventoryRequest.beforeSlotIdx)
}

// int32 changeSlotIdx = 3;
inline void CS_ChangeInventoryRequest::clear_changeslotidx() {
  _impl_.changeslotidx_ = 0;
}
inline int32_t CS_ChangeInventoryRequest::_internal_changeslotidx() const {
  return _impl_.changeslotidx_;
}
inline int32_t CS_ChangeInventoryRequest::changeslotidx() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_ChangeInventoryRequest.changeSlotIdx)
  return _internal_changeslotidx();
}
inline void CS_ChangeInventoryRequest::_internal_set_changeslotidx(int32_t value) {
  
  _impl_.changeslotidx_ = value;
}
inline void CS_ChangeInventoryRequest::set_changeslotidx(int32_t value) {
  _internal_set_changeslotidx(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_ChangeInventoryRequest.changeSlotIdx)
}

// -------------------------------------------------------------------

// SC_ChangeInventoryResponse

// int32 success = 1;
inline void SC_ChangeInventoryResponse::clear_success() {
  _impl_.success_ = 0;
}
inline int32_t SC_ChangeInventoryResponse::_internal_success() const {
  return _impl_.success_;
}
inline int32_t SC_ChangeInventoryResponse::success() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_ChangeInventoryResponse.success)
  return _internal_success();
}
inline void SC_ChangeInventoryResponse::_internal_set_success(int32_t value) {
  
  _impl_.success_ = value;
}
inline void SC_ChangeInventoryResponse::set_success(int32_t value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_ChangeInventoryResponse.success)
}

// -------------------------------------------------------------------

// CS_ItemQuickSlotChangeRequest

// int32 userSeq = 1;
inline void CS_ItemQuickSlotChangeRequest::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t CS_ItemQuickSlotChangeRequest::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t CS_ItemQuickSlotChangeRequest::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_ItemQuickSlotChangeRequest.userSeq)
  return _internal_userseq();
}
inline void CS_ItemQuickSlotChangeRequest::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void CS_ItemQuickSlotChangeRequest::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_ItemQuickSlotChangeRequest.userSeq)
}

// int64 itemId = 2;
inline void CS_ItemQuickSlotChangeRequest::clear_itemid() {
  _impl_.itemid_ = int64_t{0};
}
inline int64_t CS_ItemQuickSlotChangeRequest::_internal_itemid() const {
  return _impl_.itemid_;
}
inline int64_t CS_ItemQuickSlotChangeRequest::itemid() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_ItemQuickSlotChangeRequest.itemId)
  return _internal_itemid();
}
inline void CS_ItemQuickSlotChangeRequest::_internal_set_itemid(int64_t value) {
  
  _impl_.itemid_ = value;
}
inline void CS_ItemQuickSlotChangeRequest::set_itemid(int64_t value) {
  _internal_set_itemid(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_ItemQuickSlotChangeRequest.itemId)
}

// int32 conIdx = 3;
inline void CS_ItemQuickSlotChangeRequest::clear_conidx() {
  _impl_.conidx_ = 0;
}
inline int32_t CS_ItemQuickSlotChangeRequest::_internal_conidx() const {
  return _impl_.conidx_;
}
inline int32_t CS_ItemQuickSlotChangeRequest::conidx() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_ItemQuickSlotChangeRequest.conIdx)
  return _internal_conidx();
}
inline void CS_ItemQuickSlotChangeRequest::_internal_set_conidx(int32_t value) {
  
  _impl_.conidx_ = value;
}
inline void CS_ItemQuickSlotChangeRequest::set_conidx(int32_t value) {
  _internal_set_conidx(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_ItemQuickSlotChangeRequest.conIdx)
}

// -------------------------------------------------------------------

// SC_ItemQuickSlotChangeResponse

// int32 success = 1;
inline void SC_ItemQuickSlotChangeResponse::clear_success() {
  _impl_.success_ = 0;
}
inline int32_t SC_ItemQuickSlotChangeResponse::_internal_success() const {
  return _impl_.success_;
}
inline int32_t SC_ItemQuickSlotChangeResponse::success() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_ItemQuickSlotChangeResponse.success)
  return _internal_success();
}
inline void SC_ItemQuickSlotChangeResponse::_internal_set_success(int32_t value) {
  
  _impl_.success_ = value;
}
inline void SC_ItemQuickSlotChangeResponse::set_success(int32_t value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_ItemQuickSlotChangeResponse.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Item_2eproto
