// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NPC.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_NPC_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_NPC_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "NPCStruct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_NPC_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_NPC_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NPC_2eproto;
namespace Protocol {
class NPCInfoRequest;
struct NPCInfoRequestDefaultTypeInternal;
extern NPCInfoRequestDefaultTypeInternal _NPCInfoRequest_default_instance_;
class NPCInfoResponse;
struct NPCInfoResponseDefaultTypeInternal;
extern NPCInfoResponseDefaultTypeInternal _NPCInfoResponse_default_instance_;
class QuestCheckRequest;
struct QuestCheckRequestDefaultTypeInternal;
extern QuestCheckRequestDefaultTypeInternal _QuestCheckRequest_default_instance_;
class QuestCheckResponse;
struct QuestCheckResponseDefaultTypeInternal;
extern QuestCheckResponseDefaultTypeInternal _QuestCheckResponse_default_instance_;
class UserQuestInfoRequest;
struct UserQuestInfoRequestDefaultTypeInternal;
extern UserQuestInfoRequestDefaultTypeInternal _UserQuestInfoRequest_default_instance_;
class UserQuestInfoResponse;
struct UserQuestInfoResponseDefaultTypeInternal;
extern UserQuestInfoResponseDefaultTypeInternal _UserQuestInfoResponse_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::NPCInfoRequest* Arena::CreateMaybeMessage<::Protocol::NPCInfoRequest>(Arena*);
template<> ::Protocol::NPCInfoResponse* Arena::CreateMaybeMessage<::Protocol::NPCInfoResponse>(Arena*);
template<> ::Protocol::QuestCheckRequest* Arena::CreateMaybeMessage<::Protocol::QuestCheckRequest>(Arena*);
template<> ::Protocol::QuestCheckResponse* Arena::CreateMaybeMessage<::Protocol::QuestCheckResponse>(Arena*);
template<> ::Protocol::UserQuestInfoRequest* Arena::CreateMaybeMessage<::Protocol::UserQuestInfoRequest>(Arena*);
template<> ::Protocol::UserQuestInfoResponse* Arena::CreateMaybeMessage<::Protocol::UserQuestInfoResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class NPCInfoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.NPCInfoRequest) */ {
 public:
  inline NPCInfoRequest() : NPCInfoRequest(nullptr) {}
  ~NPCInfoRequest() override;
  explicit PROTOBUF_CONSTEXPR NPCInfoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NPCInfoRequest(const NPCInfoRequest& from);
  NPCInfoRequest(NPCInfoRequest&& from) noexcept
    : NPCInfoRequest() {
    *this = ::std::move(from);
  }

  inline NPCInfoRequest& operator=(const NPCInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline NPCInfoRequest& operator=(NPCInfoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NPCInfoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const NPCInfoRequest* internal_default_instance() {
    return reinterpret_cast<const NPCInfoRequest*>(
               &_NPCInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NPCInfoRequest& a, NPCInfoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(NPCInfoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NPCInfoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NPCInfoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NPCInfoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NPCInfoRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NPCInfoRequest& from) {
    NPCInfoRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NPCInfoRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.NPCInfoRequest";
  }
  protected:
  explicit NPCInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMapIdFieldNumber = 1,
  };
  // int64 mapId = 1;
  void clear_mapid();
  int64_t mapid() const;
  void set_mapid(int64_t value);
  private:
  int64_t _internal_mapid() const;
  void _internal_set_mapid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.NPCInfoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t mapid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NPC_2eproto;
};
// -------------------------------------------------------------------

class NPCInfoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.NPCInfoResponse) */ {
 public:
  inline NPCInfoResponse() : NPCInfoResponse(nullptr) {}
  ~NPCInfoResponse() override;
  explicit PROTOBUF_CONSTEXPR NPCInfoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NPCInfoResponse(const NPCInfoResponse& from);
  NPCInfoResponse(NPCInfoResponse&& from) noexcept
    : NPCInfoResponse() {
    *this = ::std::move(from);
  }

  inline NPCInfoResponse& operator=(const NPCInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline NPCInfoResponse& operator=(NPCInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NPCInfoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const NPCInfoResponse* internal_default_instance() {
    return reinterpret_cast<const NPCInfoResponse*>(
               &_NPCInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(NPCInfoResponse& a, NPCInfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(NPCInfoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NPCInfoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NPCInfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NPCInfoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NPCInfoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NPCInfoResponse& from) {
    NPCInfoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NPCInfoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.NPCInfoResponse";
  }
  protected:
  explicit NPCInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNpcFieldNumber = 1,
  };
  // repeated .Protocol.NPC npc = 1;
  int npc_size() const;
  private:
  int _internal_npc_size() const;
  public:
  void clear_npc();
  ::Protocol::NPC* mutable_npc(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC >*
      mutable_npc();
  private:
  const ::Protocol::NPC& _internal_npc(int index) const;
  ::Protocol::NPC* _internal_add_npc();
  public:
  const ::Protocol::NPC& npc(int index) const;
  ::Protocol::NPC* add_npc();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC >&
      npc() const;

  // @@protoc_insertion_point(class_scope:Protocol.NPCInfoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC > npc_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NPC_2eproto;
};
// -------------------------------------------------------------------

class UserQuestInfoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.UserQuestInfoRequest) */ {
 public:
  inline UserQuestInfoRequest() : UserQuestInfoRequest(nullptr) {}
  ~UserQuestInfoRequest() override;
  explicit PROTOBUF_CONSTEXPR UserQuestInfoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UserQuestInfoRequest(const UserQuestInfoRequest& from);
  UserQuestInfoRequest(UserQuestInfoRequest&& from) noexcept
    : UserQuestInfoRequest() {
    *this = ::std::move(from);
  }

  inline UserQuestInfoRequest& operator=(const UserQuestInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserQuestInfoRequest& operator=(UserQuestInfoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserQuestInfoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserQuestInfoRequest* internal_default_instance() {
    return reinterpret_cast<const UserQuestInfoRequest*>(
               &_UserQuestInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UserQuestInfoRequest& a, UserQuestInfoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UserQuestInfoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserQuestInfoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserQuestInfoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UserQuestInfoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UserQuestInfoRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UserQuestInfoRequest& from) {
    UserQuestInfoRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserQuestInfoRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.UserQuestInfoRequest";
  }
  protected:
  explicit UserQuestInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserSeqFieldNumber = 1,
  };
  // int32 userSeq = 1;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.UserQuestInfoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NPC_2eproto;
};
// -------------------------------------------------------------------

class UserQuestInfoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.UserQuestInfoResponse) */ {
 public:
  inline UserQuestInfoResponse() : UserQuestInfoResponse(nullptr) {}
  ~UserQuestInfoResponse() override;
  explicit PROTOBUF_CONSTEXPR UserQuestInfoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UserQuestInfoResponse(const UserQuestInfoResponse& from);
  UserQuestInfoResponse(UserQuestInfoResponse&& from) noexcept
    : UserQuestInfoResponse() {
    *this = ::std::move(from);
  }

  inline UserQuestInfoResponse& operator=(const UserQuestInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserQuestInfoResponse& operator=(UserQuestInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserQuestInfoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserQuestInfoResponse* internal_default_instance() {
    return reinterpret_cast<const UserQuestInfoResponse*>(
               &_UserQuestInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(UserQuestInfoResponse& a, UserQuestInfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(UserQuestInfoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserQuestInfoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserQuestInfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UserQuestInfoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UserQuestInfoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UserQuestInfoResponse& from) {
    UserQuestInfoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserQuestInfoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.UserQuestInfoResponse";
  }
  protected:
  explicit UserQuestInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestsFieldNumber = 1,
  };
  // repeated .Protocol.Quest quests = 1;
  int quests_size() const;
  private:
  int _internal_quests_size() const;
  public:
  void clear_quests();
  ::Protocol::Quest* mutable_quests(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Quest >*
      mutable_quests();
  private:
  const ::Protocol::Quest& _internal_quests(int index) const;
  ::Protocol::Quest* _internal_add_quests();
  public:
  const ::Protocol::Quest& quests(int index) const;
  ::Protocol::Quest* add_quests();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Quest >&
      quests() const;

  // @@protoc_insertion_point(class_scope:Protocol.UserQuestInfoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Quest > quests_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NPC_2eproto;
};
// -------------------------------------------------------------------

class QuestCheckRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.QuestCheckRequest) */ {
 public:
  inline QuestCheckRequest() : QuestCheckRequest(nullptr) {}
  ~QuestCheckRequest() override;
  explicit PROTOBUF_CONSTEXPR QuestCheckRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QuestCheckRequest(const QuestCheckRequest& from);
  QuestCheckRequest(QuestCheckRequest&& from) noexcept
    : QuestCheckRequest() {
    *this = ::std::move(from);
  }

  inline QuestCheckRequest& operator=(const QuestCheckRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuestCheckRequest& operator=(QuestCheckRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QuestCheckRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const QuestCheckRequest* internal_default_instance() {
    return reinterpret_cast<const QuestCheckRequest*>(
               &_QuestCheckRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(QuestCheckRequest& a, QuestCheckRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(QuestCheckRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuestCheckRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QuestCheckRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QuestCheckRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QuestCheckRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const QuestCheckRequest& from) {
    QuestCheckRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QuestCheckRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.QuestCheckRequest";
  }
  protected:
  explicit QuestCheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestSeqFieldNumber = 1,
    kUserSeqFieldNumber = 2,
  };
  // int32 questSeq = 1;
  void clear_questseq();
  int32_t questseq() const;
  void set_questseq(int32_t value);
  private:
  int32_t _internal_questseq() const;
  void _internal_set_questseq(int32_t value);
  public:

  // int32 userSeq = 2;
  void clear_userseq();
  int32_t userseq() const;
  void set_userseq(int32_t value);
  private:
  int32_t _internal_userseq() const;
  void _internal_set_userseq(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.QuestCheckRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t questseq_;
    int32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NPC_2eproto;
};
// -------------------------------------------------------------------

class QuestCheckResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.QuestCheckResponse) */ {
 public:
  inline QuestCheckResponse() : QuestCheckResponse(nullptr) {}
  ~QuestCheckResponse() override;
  explicit PROTOBUF_CONSTEXPR QuestCheckResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QuestCheckResponse(const QuestCheckResponse& from);
  QuestCheckResponse(QuestCheckResponse&& from) noexcept
    : QuestCheckResponse() {
    *this = ::std::move(from);
  }

  inline QuestCheckResponse& operator=(const QuestCheckResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuestCheckResponse& operator=(QuestCheckResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QuestCheckResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const QuestCheckResponse* internal_default_instance() {
    return reinterpret_cast<const QuestCheckResponse*>(
               &_QuestCheckResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(QuestCheckResponse& a, QuestCheckResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(QuestCheckResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuestCheckResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QuestCheckResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QuestCheckResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QuestCheckResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const QuestCheckResponse& from) {
    QuestCheckResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QuestCheckResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.QuestCheckResponse";
  }
  protected:
  explicit QuestCheckResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestSeqFieldNumber = 1,
    kQueststateFieldNumber = 2,
  };
  // int32 questSeq = 1;
  void clear_questseq();
  int32_t questseq() const;
  void set_questseq(int32_t value);
  private:
  int32_t _internal_questseq() const;
  void _internal_set_questseq(int32_t value);
  public:

  // .Protocol.QuestState queststate = 2;
  void clear_queststate();
  ::Protocol::QuestState queststate() const;
  void set_queststate(::Protocol::QuestState value);
  private:
  ::Protocol::QuestState _internal_queststate() const;
  void _internal_set_queststate(::Protocol::QuestState value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.QuestCheckResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t questseq_;
    int queststate_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NPC_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NPCInfoRequest

// int64 mapId = 1;
inline void NPCInfoRequest::clear_mapid() {
  _impl_.mapid_ = int64_t{0};
}
inline int64_t NPCInfoRequest::_internal_mapid() const {
  return _impl_.mapid_;
}
inline int64_t NPCInfoRequest::mapid() const {
  // @@protoc_insertion_point(field_get:Protocol.NPCInfoRequest.mapId)
  return _internal_mapid();
}
inline void NPCInfoRequest::_internal_set_mapid(int64_t value) {
  
  _impl_.mapid_ = value;
}
inline void NPCInfoRequest::set_mapid(int64_t value) {
  _internal_set_mapid(value);
  // @@protoc_insertion_point(field_set:Protocol.NPCInfoRequest.mapId)
}

// -------------------------------------------------------------------

// NPCInfoResponse

// repeated .Protocol.NPC npc = 1;
inline int NPCInfoResponse::_internal_npc_size() const {
  return _impl_.npc_.size();
}
inline int NPCInfoResponse::npc_size() const {
  return _internal_npc_size();
}
inline ::Protocol::NPC* NPCInfoResponse::mutable_npc(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.NPCInfoResponse.npc)
  return _impl_.npc_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC >*
NPCInfoResponse::mutable_npc() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.NPCInfoResponse.npc)
  return &_impl_.npc_;
}
inline const ::Protocol::NPC& NPCInfoResponse::_internal_npc(int index) const {
  return _impl_.npc_.Get(index);
}
inline const ::Protocol::NPC& NPCInfoResponse::npc(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.NPCInfoResponse.npc)
  return _internal_npc(index);
}
inline ::Protocol::NPC* NPCInfoResponse::_internal_add_npc() {
  return _impl_.npc_.Add();
}
inline ::Protocol::NPC* NPCInfoResponse::add_npc() {
  ::Protocol::NPC* _add = _internal_add_npc();
  // @@protoc_insertion_point(field_add:Protocol.NPCInfoResponse.npc)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC >&
NPCInfoResponse::npc() const {
  // @@protoc_insertion_point(field_list:Protocol.NPCInfoResponse.npc)
  return _impl_.npc_;
}

// -------------------------------------------------------------------

// UserQuestInfoRequest

// int32 userSeq = 1;
inline void UserQuestInfoRequest::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t UserQuestInfoRequest::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t UserQuestInfoRequest::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.UserQuestInfoRequest.userSeq)
  return _internal_userseq();
}
inline void UserQuestInfoRequest::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void UserQuestInfoRequest::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.UserQuestInfoRequest.userSeq)
}

// -------------------------------------------------------------------

// UserQuestInfoResponse

// repeated .Protocol.Quest quests = 1;
inline int UserQuestInfoResponse::_internal_quests_size() const {
  return _impl_.quests_.size();
}
inline int UserQuestInfoResponse::quests_size() const {
  return _internal_quests_size();
}
inline ::Protocol::Quest* UserQuestInfoResponse::mutable_quests(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.UserQuestInfoResponse.quests)
  return _impl_.quests_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Quest >*
UserQuestInfoResponse::mutable_quests() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.UserQuestInfoResponse.quests)
  return &_impl_.quests_;
}
inline const ::Protocol::Quest& UserQuestInfoResponse::_internal_quests(int index) const {
  return _impl_.quests_.Get(index);
}
inline const ::Protocol::Quest& UserQuestInfoResponse::quests(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.UserQuestInfoResponse.quests)
  return _internal_quests(index);
}
inline ::Protocol::Quest* UserQuestInfoResponse::_internal_add_quests() {
  return _impl_.quests_.Add();
}
inline ::Protocol::Quest* UserQuestInfoResponse::add_quests() {
  ::Protocol::Quest* _add = _internal_add_quests();
  // @@protoc_insertion_point(field_add:Protocol.UserQuestInfoResponse.quests)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Quest >&
UserQuestInfoResponse::quests() const {
  // @@protoc_insertion_point(field_list:Protocol.UserQuestInfoResponse.quests)
  return _impl_.quests_;
}

// -------------------------------------------------------------------

// QuestCheckRequest

// int32 questSeq = 1;
inline void QuestCheckRequest::clear_questseq() {
  _impl_.questseq_ = 0;
}
inline int32_t QuestCheckRequest::_internal_questseq() const {
  return _impl_.questseq_;
}
inline int32_t QuestCheckRequest::questseq() const {
  // @@protoc_insertion_point(field_get:Protocol.QuestCheckRequest.questSeq)
  return _internal_questseq();
}
inline void QuestCheckRequest::_internal_set_questseq(int32_t value) {
  
  _impl_.questseq_ = value;
}
inline void QuestCheckRequest::set_questseq(int32_t value) {
  _internal_set_questseq(value);
  // @@protoc_insertion_point(field_set:Protocol.QuestCheckRequest.questSeq)
}

// int32 userSeq = 2;
inline void QuestCheckRequest::clear_userseq() {
  _impl_.userseq_ = 0;
}
inline int32_t QuestCheckRequest::_internal_userseq() const {
  return _impl_.userseq_;
}
inline int32_t QuestCheckRequest::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.QuestCheckRequest.userSeq)
  return _internal_userseq();
}
inline void QuestCheckRequest::_internal_set_userseq(int32_t value) {
  
  _impl_.userseq_ = value;
}
inline void QuestCheckRequest::set_userseq(int32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.QuestCheckRequest.userSeq)
}

// -------------------------------------------------------------------

// QuestCheckResponse

// int32 questSeq = 1;
inline void QuestCheckResponse::clear_questseq() {
  _impl_.questseq_ = 0;
}
inline int32_t QuestCheckResponse::_internal_questseq() const {
  return _impl_.questseq_;
}
inline int32_t QuestCheckResponse::questseq() const {
  // @@protoc_insertion_point(field_get:Protocol.QuestCheckResponse.questSeq)
  return _internal_questseq();
}
inline void QuestCheckResponse::_internal_set_questseq(int32_t value) {
  
  _impl_.questseq_ = value;
}
inline void QuestCheckResponse::set_questseq(int32_t value) {
  _internal_set_questseq(value);
  // @@protoc_insertion_point(field_set:Protocol.QuestCheckResponse.questSeq)
}

// .Protocol.QuestState queststate = 2;
inline void QuestCheckResponse::clear_queststate() {
  _impl_.queststate_ = 0;
}
inline ::Protocol::QuestState QuestCheckResponse::_internal_queststate() const {
  return static_cast< ::Protocol::QuestState >(_impl_.queststate_);
}
inline ::Protocol::QuestState QuestCheckResponse::queststate() const {
  // @@protoc_insertion_point(field_get:Protocol.QuestCheckResponse.queststate)
  return _internal_queststate();
}
inline void QuestCheckResponse::_internal_set_queststate(::Protocol::QuestState value) {
  
  _impl_.queststate_ = value;
}
inline void QuestCheckResponse::set_queststate(::Protocol::QuestState value) {
  _internal_set_queststate(value);
  // @@protoc_insertion_point(field_set:Protocol.QuestCheckResponse.queststate)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_NPC_2eproto
