// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

#include "Packet.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR PacketHeader::PacketHeader(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PacketHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketHeaderDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketHeaderDefaultTypeInternal() {}
  union {
    PacketHeader _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketHeaderDefaultTypeInternal _PacketHeader_default_instance_;
PROTOBUF_CONSTEXPR C_ITEM_ADD::C_ITEM_ADD(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.item_)*/nullptr
  , /*decltype(_impl_.userseq_)*/0u
  , /*decltype(_impl_.item_data_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct C_ITEM_ADDDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_ITEM_ADDDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_ITEM_ADDDefaultTypeInternal() {}
  union {
    C_ITEM_ADD _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_ITEM_ADDDefaultTypeInternal _C_ITEM_ADD_default_instance_;
PROTOBUF_CONSTEXPR S_ITEM_ADD::S_ITEM_ADD(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S_ITEM_ADDDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_ITEM_ADDDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_ITEM_ADDDefaultTypeInternal() {}
  union {
    S_ITEM_ADD _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_ITEM_ADDDefaultTypeInternal _S_ITEM_ADD_default_instance_;
PROTOBUF_CONSTEXPR C_ITEM_USE::C_ITEM_USE(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.userseq_)*/0u
  , /*decltype(_impl_.itemseq_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C_ITEM_USEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_ITEM_USEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_ITEM_USEDefaultTypeInternal() {}
  union {
    C_ITEM_USE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_ITEM_USEDefaultTypeInternal _C_ITEM_USE_default_instance_;
PROTOBUF_CONSTEXPR S_ITEM_USE::S_ITEM_USE(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S_ITEM_USEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_ITEM_USEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_ITEM_USEDefaultTypeInternal() {}
  union {
    S_ITEM_USE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_ITEM_USEDefaultTypeInternal _S_ITEM_USE_default_instance_;
PROTOBUF_CONSTEXPR InventoryRequestPacket::InventoryRequestPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.userseq_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InventoryRequestPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InventoryRequestPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InventoryRequestPacketDefaultTypeInternal() {}
  union {
    InventoryRequestPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InventoryRequestPacketDefaultTypeInternal _InventoryRequestPacket_default_instance_;
PROTOBUF_CONSTEXPR InventoryResponsePacket::InventoryResponsePacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.items_)*/{}
  , /*decltype(_impl_.userseq_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InventoryResponsePacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InventoryResponsePacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InventoryResponsePacketDefaultTypeInternal() {}
  union {
    InventoryResponsePacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InventoryResponsePacketDefaultTypeInternal _InventoryResponsePacket_default_instance_;
PROTOBUF_CONSTEXPR LoginRequestPacket::LoginRequestPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.playerid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.playerseq_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LoginRequestPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginRequestPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginRequestPacketDefaultTypeInternal() {}
  union {
    LoginRequestPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginRequestPacketDefaultTypeInternal _LoginRequestPacket_default_instance_;
PROTOBUF_CONSTEXPR LoginResponsePacket::LoginResponsePacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.gameserveraddress_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.playerseq_)*/0u
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_.gameserverport_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LoginResponsePacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginResponsePacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginResponsePacketDefaultTypeInternal() {}
  union {
    LoginResponsePacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginResponsePacketDefaultTypeInternal _LoginResponsePacket_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Packet_2eproto[9];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Packet_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Packet_2eproto = nullptr;

const uint32_t TableStruct_Packet_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::PacketHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::PacketHeader, _impl_.type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_ITEM_ADD, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_ITEM_ADD, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_ITEM_ADD, _impl_.userseq_),
  PROTOBUF_FIELD_OFFSET(::Protocol::C_ITEM_ADD, _impl_.item_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::Protocol::C_ITEM_ADD, _impl_.item_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_ITEM_ADD, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_ITEM_ADD, _impl_.success_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_ITEM_USE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_ITEM_USE, _impl_.userseq_),
  PROTOBUF_FIELD_OFFSET(::Protocol::C_ITEM_USE, _impl_.itemseq_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_ITEM_USE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_ITEM_USE, _impl_.success_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::InventoryRequestPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::InventoryRequestPacket, _impl_.userseq_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::InventoryResponsePacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::InventoryResponsePacket, _impl_.userseq_),
  PROTOBUF_FIELD_OFFSET(::Protocol::InventoryResponsePacket, _impl_.items_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginRequestPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginRequestPacket, _impl_.playerseq_),
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginRequestPacket, _impl_.playerid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginResponsePacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginResponsePacket, _impl_.playerseq_),
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginResponsePacket, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginResponsePacket, _impl_.gameserveraddress_),
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginResponsePacket, _impl_.gameserverport_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::PacketHeader)},
  { 7, -1, -1, sizeof(::Protocol::C_ITEM_ADD)},
  { 19, -1, -1, sizeof(::Protocol::S_ITEM_ADD)},
  { 26, -1, -1, sizeof(::Protocol::C_ITEM_USE)},
  { 34, -1, -1, sizeof(::Protocol::S_ITEM_USE)},
  { 41, -1, -1, sizeof(::Protocol::InventoryRequestPacket)},
  { 48, -1, -1, sizeof(::Protocol::InventoryResponsePacket)},
  { 56, -1, -1, sizeof(::Protocol::LoginRequestPacket)},
  { 64, -1, -1, sizeof(::Protocol::LoginResponsePacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_PacketHeader_default_instance_._instance,
  &::Protocol::_C_ITEM_ADD_default_instance_._instance,
  &::Protocol::_S_ITEM_ADD_default_instance_._instance,
  &::Protocol::_C_ITEM_USE_default_instance_._instance,
  &::Protocol::_S_ITEM_USE_default_instance_._instance,
  &::Protocol::_InventoryRequestPacket_default_instance_._instance,
  &::Protocol::_InventoryResponsePacket_default_instance_._instance,
  &::Protocol::_LoginRequestPacket_default_instance_._instance,
  &::Protocol::_LoginResponsePacket_default_instance_._instance,
};

const char descriptor_table_protodef_Packet_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Packet.proto\022\010Protocol\032\014Struct.proto\"\034"
  "\n\014PacketHeader\022\014\n\004type\030\001 \001(\005\"\272\001\n\nC_ITEM_"
  "ADD\022\017\n\007userSeq\030\001 \001(\r\022\034\n\004item\030\002 \001(\0132\016.Pro"
  "tocol.Item\022 \n\005equip\030\003 \001(\0132\017.Protocol.Equ"
  "ipH\000\022,\n\013consumption\030\004 \001(\0132\025.Protocol.Con"
  "sumptionH\000\022 \n\003etc\030\005 \001(\0132\021.Protocol.EtcIt"
  "emH\000B\013\n\titem_data\"\035\n\nS_ITEM_ADD\022\017\n\007succe"
  "ss\030\001 \001(\010\".\n\nC_ITEM_USE\022\017\n\007userSeq\030\001 \001(\r\022"
  "\017\n\007itemSeq\030\002 \001(\005\"\035\n\nS_ITEM_USE\022\017\n\007succes"
  "s\030\001 \001(\010\")\n\026InventoryRequestPacket\022\017\n\007use"
  "rSeq\030\001 \001(\r\"I\n\027InventoryResponsePacket\022\017\n"
  "\007userSeq\030\001 \001(\r\022\035\n\005items\030\002 \003(\0132\016.Protocol"
  ".Item\"9\n\022LoginRequestPacket\022\021\n\tplayerSeq"
  "\030\001 \001(\r\022\020\n\010playerId\030\002 \001(\t\"l\n\023LoginRespons"
  "ePacket\022\021\n\tplayerSeq\030\001 \001(\r\022\017\n\007success\030\002 "
  "\001(\010\022\031\n\021gameServerAddress\030\003 \001(\t\022\026\n\016gameSe"
  "rverPort\030\004 \001(\005b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Packet_2eproto_deps[1] = {
  &::descriptor_table_Struct_2eproto,
};
static ::_pbi::once_flag descriptor_table_Packet_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Packet_2eproto = {
    false, false, 662, descriptor_table_protodef_Packet_2eproto,
    "Packet.proto",
    &descriptor_table_Packet_2eproto_once, descriptor_table_Packet_2eproto_deps, 1, 9,
    schemas, file_default_instances, TableStruct_Packet_2eproto::offsets,
    file_level_metadata_Packet_2eproto, file_level_enum_descriptors_Packet_2eproto,
    file_level_service_descriptors_Packet_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Packet_2eproto_getter() {
  return &descriptor_table_Packet_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Packet_2eproto(&descriptor_table_Packet_2eproto);
namespace Protocol {

// ===================================================================

class PacketHeader::_Internal {
 public:
};

PacketHeader::PacketHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.PacketHeader)
}
PacketHeader::PacketHeader(const PacketHeader& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PacketHeader* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:Protocol.PacketHeader)
}

inline void PacketHeader::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PacketHeader::~PacketHeader() {
  // @@protoc_insertion_point(destructor:Protocol.PacketHeader)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PacketHeader::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PacketHeader::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PacketHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.PacketHeader)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PacketHeader::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PacketHeader::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.PacketHeader)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.PacketHeader)
  return target;
}

size_t PacketHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.PacketHeader)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 type = 1;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PacketHeader::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PacketHeader::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PacketHeader::GetClassData() const { return &_class_data_; }


void PacketHeader::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PacketHeader*>(&to_msg);
  auto& from = static_cast<const PacketHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.PacketHeader)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PacketHeader::CopyFrom(const PacketHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.PacketHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PacketHeader::IsInitialized() const {
  return true;
}

void PacketHeader::InternalSwap(PacketHeader* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PacketHeader::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[0]);
}

// ===================================================================

class C_ITEM_ADD::_Internal {
 public:
  static const ::Protocol::Item& item(const C_ITEM_ADD* msg);
  static const ::Protocol::Equip& equip(const C_ITEM_ADD* msg);
  static const ::Protocol::Consumption& consumption(const C_ITEM_ADD* msg);
  static const ::Protocol::EtcItem& etc(const C_ITEM_ADD* msg);
};

const ::Protocol::Item&
C_ITEM_ADD::_Internal::item(const C_ITEM_ADD* msg) {
  return *msg->_impl_.item_;
}
const ::Protocol::Equip&
C_ITEM_ADD::_Internal::equip(const C_ITEM_ADD* msg) {
  return *msg->_impl_.item_data_.equip_;
}
const ::Protocol::Consumption&
C_ITEM_ADD::_Internal::consumption(const C_ITEM_ADD* msg) {
  return *msg->_impl_.item_data_.consumption_;
}
const ::Protocol::EtcItem&
C_ITEM_ADD::_Internal::etc(const C_ITEM_ADD* msg) {
  return *msg->_impl_.item_data_.etc_;
}
void C_ITEM_ADD::clear_item() {
  if (GetArenaForAllocation() == nullptr && _impl_.item_ != nullptr) {
    delete _impl_.item_;
  }
  _impl_.item_ = nullptr;
}
void C_ITEM_ADD::set_allocated_equip(::Protocol::Equip* equip) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_item_data();
  if (equip) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(equip));
    if (message_arena != submessage_arena) {
      equip = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, equip, submessage_arena);
    }
    set_has_equip();
    _impl_.item_data_.equip_ = equip;
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_ITEM_ADD.equip)
}
void C_ITEM_ADD::clear_equip() {
  if (_internal_has_equip()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.item_data_.equip_;
    }
    clear_has_item_data();
  }
}
void C_ITEM_ADD::set_allocated_consumption(::Protocol::Consumption* consumption) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_item_data();
  if (consumption) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(consumption));
    if (message_arena != submessage_arena) {
      consumption = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, consumption, submessage_arena);
    }
    set_has_consumption();
    _impl_.item_data_.consumption_ = consumption;
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_ITEM_ADD.consumption)
}
void C_ITEM_ADD::clear_consumption() {
  if (_internal_has_consumption()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.item_data_.consumption_;
    }
    clear_has_item_data();
  }
}
void C_ITEM_ADD::set_allocated_etc(::Protocol::EtcItem* etc) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_item_data();
  if (etc) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(etc));
    if (message_arena != submessage_arena) {
      etc = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, etc, submessage_arena);
    }
    set_has_etc();
    _impl_.item_data_.etc_ = etc;
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_ITEM_ADD.etc)
}
void C_ITEM_ADD::clear_etc() {
  if (_internal_has_etc()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.item_data_.etc_;
    }
    clear_has_item_data();
  }
}
C_ITEM_ADD::C_ITEM_ADD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.C_ITEM_ADD)
}
C_ITEM_ADD::C_ITEM_ADD(const C_ITEM_ADD& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C_ITEM_ADD* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.item_){nullptr}
    , decltype(_impl_.userseq_){}
    , decltype(_impl_.item_data_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_item()) {
    _this->_impl_.item_ = new ::Protocol::Item(*from._impl_.item_);
  }
  _this->_impl_.userseq_ = from._impl_.userseq_;
  clear_has_item_data();
  switch (from.item_data_case()) {
    case kEquip: {
      _this->_internal_mutable_equip()->::Protocol::Equip::MergeFrom(
          from._internal_equip());
      break;
    }
    case kConsumption: {
      _this->_internal_mutable_consumption()->::Protocol::Consumption::MergeFrom(
          from._internal_consumption());
      break;
    }
    case kEtc: {
      _this->_internal_mutable_etc()->::Protocol::EtcItem::MergeFrom(
          from._internal_etc());
      break;
    }
    case ITEM_DATA_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.C_ITEM_ADD)
}

inline void C_ITEM_ADD::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.item_){nullptr}
    , decltype(_impl_.userseq_){0u}
    , decltype(_impl_.item_data_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_item_data();
}

C_ITEM_ADD::~C_ITEM_ADD() {
  // @@protoc_insertion_point(destructor:Protocol.C_ITEM_ADD)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_ITEM_ADD::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.item_;
  if (has_item_data()) {
    clear_item_data();
  }
}

void C_ITEM_ADD::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C_ITEM_ADD::clear_item_data() {
// @@protoc_insertion_point(one_of_clear_start:Protocol.C_ITEM_ADD)
  switch (item_data_case()) {
    case kEquip: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.item_data_.equip_;
      }
      break;
    }
    case kConsumption: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.item_data_.consumption_;
      }
      break;
    }
    case kEtc: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.item_data_.etc_;
      }
      break;
    }
    case ITEM_DATA_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ITEM_DATA_NOT_SET;
}


void C_ITEM_ADD::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C_ITEM_ADD)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.item_ != nullptr) {
    delete _impl_.item_;
  }
  _impl_.item_ = nullptr;
  _impl_.userseq_ = 0u;
  clear_item_data();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_ITEM_ADD::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 userSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.Item item = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_item(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.Equip equip = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_equip(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.Consumption consumption = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_consumption(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.EtcItem etc = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_etc(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_ITEM_ADD::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C_ITEM_ADD)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_userseq(), target);
  }

  // .Protocol.Item item = 2;
  if (this->_internal_has_item()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::item(this),
        _Internal::item(this).GetCachedSize(), target, stream);
  }

  // .Protocol.Equip equip = 3;
  if (_internal_has_equip()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::equip(this),
        _Internal::equip(this).GetCachedSize(), target, stream);
  }

  // .Protocol.Consumption consumption = 4;
  if (_internal_has_consumption()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::consumption(this),
        _Internal::consumption(this).GetCachedSize(), target, stream);
  }

  // .Protocol.EtcItem etc = 5;
  if (_internal_has_etc()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::etc(this),
        _Internal::etc(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C_ITEM_ADD)
  return target;
}

size_t C_ITEM_ADD::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C_ITEM_ADD)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.Item item = 2;
  if (this->_internal_has_item()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.item_);
  }

  // uint32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_userseq());
  }

  switch (item_data_case()) {
    // .Protocol.Equip equip = 3;
    case kEquip: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.item_data_.equip_);
      break;
    }
    // .Protocol.Consumption consumption = 4;
    case kConsumption: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.item_data_.consumption_);
      break;
    }
    // .Protocol.EtcItem etc = 5;
    case kEtc: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.item_data_.etc_);
      break;
    }
    case ITEM_DATA_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_ITEM_ADD::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C_ITEM_ADD::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_ITEM_ADD::GetClassData() const { return &_class_data_; }


void C_ITEM_ADD::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C_ITEM_ADD*>(&to_msg);
  auto& from = static_cast<const C_ITEM_ADD&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C_ITEM_ADD)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_item()) {
    _this->_internal_mutable_item()->::Protocol::Item::MergeFrom(
        from._internal_item());
  }
  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  switch (from.item_data_case()) {
    case kEquip: {
      _this->_internal_mutable_equip()->::Protocol::Equip::MergeFrom(
          from._internal_equip());
      break;
    }
    case kConsumption: {
      _this->_internal_mutable_consumption()->::Protocol::Consumption::MergeFrom(
          from._internal_consumption());
      break;
    }
    case kEtc: {
      _this->_internal_mutable_etc()->::Protocol::EtcItem::MergeFrom(
          from._internal_etc());
      break;
    }
    case ITEM_DATA_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_ITEM_ADD::CopyFrom(const C_ITEM_ADD& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C_ITEM_ADD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_ITEM_ADD::IsInitialized() const {
  return true;
}

void C_ITEM_ADD::InternalSwap(C_ITEM_ADD* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_ITEM_ADD, _impl_.userseq_)
      + sizeof(C_ITEM_ADD::_impl_.userseq_)
      - PROTOBUF_FIELD_OFFSET(C_ITEM_ADD, _impl_.item_)>(
          reinterpret_cast<char*>(&_impl_.item_),
          reinterpret_cast<char*>(&other->_impl_.item_));
  swap(_impl_.item_data_, other->_impl_.item_data_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata C_ITEM_ADD::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[1]);
}

// ===================================================================

class S_ITEM_ADD::_Internal {
 public:
};

S_ITEM_ADD::S_ITEM_ADD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S_ITEM_ADD)
}
S_ITEM_ADD::S_ITEM_ADD(const S_ITEM_ADD& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S_ITEM_ADD* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:Protocol.S_ITEM_ADD)
}

inline void S_ITEM_ADD::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S_ITEM_ADD::~S_ITEM_ADD() {
  // @@protoc_insertion_point(destructor:Protocol.S_ITEM_ADD)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_ITEM_ADD::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void S_ITEM_ADD::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S_ITEM_ADD::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S_ITEM_ADD)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_ITEM_ADD::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr) > 0 ? 1 : 0;
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_ITEM_ADD::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S_ITEM_ADD)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S_ITEM_ADD)
  return target;
}

size_t S_ITEM_ADD::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S_ITEM_ADD)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_ITEM_ADD::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S_ITEM_ADD::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_ITEM_ADD::GetClassData() const { return &_class_data_; }


void S_ITEM_ADD::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S_ITEM_ADD*>(&to_msg);
  auto& from = static_cast<const S_ITEM_ADD&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S_ITEM_ADD)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_ITEM_ADD::CopyFrom(const S_ITEM_ADD& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S_ITEM_ADD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_ITEM_ADD::IsInitialized() const {
  return true;
}

void S_ITEM_ADD::InternalSwap(S_ITEM_ADD* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.success_, other->_impl_.success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata S_ITEM_ADD::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[2]);
}

// ===================================================================

class C_ITEM_USE::_Internal {
 public:
};

C_ITEM_USE::C_ITEM_USE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.C_ITEM_USE)
}
C_ITEM_USE::C_ITEM_USE(const C_ITEM_USE& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C_ITEM_USE* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.userseq_){}
    , decltype(_impl_.itemseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.userseq_, &from._impl_.userseq_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.itemseq_) -
    reinterpret_cast<char*>(&_impl_.userseq_)) + sizeof(_impl_.itemseq_));
  // @@protoc_insertion_point(copy_constructor:Protocol.C_ITEM_USE)
}

inline void C_ITEM_USE::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.userseq_){0u}
    , decltype(_impl_.itemseq_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C_ITEM_USE::~C_ITEM_USE() {
  // @@protoc_insertion_point(destructor:Protocol.C_ITEM_USE)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_ITEM_USE::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C_ITEM_USE::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C_ITEM_USE::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C_ITEM_USE)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.userseq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.itemseq_) -
      reinterpret_cast<char*>(&_impl_.userseq_)) + sizeof(_impl_.itemseq_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_ITEM_USE::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 userSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 itemSeq = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.itemseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_ITEM_USE::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C_ITEM_USE)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_userseq(), target);
  }

  // int32 itemSeq = 2;
  if (this->_internal_itemseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_itemseq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C_ITEM_USE)
  return target;
}

size_t C_ITEM_USE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C_ITEM_USE)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_userseq());
  }

  // int32 itemSeq = 2;
  if (this->_internal_itemseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_itemseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_ITEM_USE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C_ITEM_USE::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_ITEM_USE::GetClassData() const { return &_class_data_; }


void C_ITEM_USE::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C_ITEM_USE*>(&to_msg);
  auto& from = static_cast<const C_ITEM_USE&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C_ITEM_USE)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  if (from._internal_itemseq() != 0) {
    _this->_internal_set_itemseq(from._internal_itemseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_ITEM_USE::CopyFrom(const C_ITEM_USE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C_ITEM_USE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_ITEM_USE::IsInitialized() const {
  return true;
}

void C_ITEM_USE::InternalSwap(C_ITEM_USE* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_ITEM_USE, _impl_.itemseq_)
      + sizeof(C_ITEM_USE::_impl_.itemseq_)
      - PROTOBUF_FIELD_OFFSET(C_ITEM_USE, _impl_.userseq_)>(
          reinterpret_cast<char*>(&_impl_.userseq_),
          reinterpret_cast<char*>(&other->_impl_.userseq_));
}

::PROTOBUF_NAMESPACE_ID::Metadata C_ITEM_USE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[3]);
}

// ===================================================================

class S_ITEM_USE::_Internal {
 public:
};

S_ITEM_USE::S_ITEM_USE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S_ITEM_USE)
}
S_ITEM_USE::S_ITEM_USE(const S_ITEM_USE& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S_ITEM_USE* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:Protocol.S_ITEM_USE)
}

inline void S_ITEM_USE::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S_ITEM_USE::~S_ITEM_USE() {
  // @@protoc_insertion_point(destructor:Protocol.S_ITEM_USE)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_ITEM_USE::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void S_ITEM_USE::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S_ITEM_USE::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S_ITEM_USE)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_ITEM_USE::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr) > 0 ? 1 : 0;
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_ITEM_USE::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S_ITEM_USE)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S_ITEM_USE)
  return target;
}

size_t S_ITEM_USE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S_ITEM_USE)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_ITEM_USE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S_ITEM_USE::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_ITEM_USE::GetClassData() const { return &_class_data_; }


void S_ITEM_USE::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S_ITEM_USE*>(&to_msg);
  auto& from = static_cast<const S_ITEM_USE&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S_ITEM_USE)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_ITEM_USE::CopyFrom(const S_ITEM_USE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S_ITEM_USE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_ITEM_USE::IsInitialized() const {
  return true;
}

void S_ITEM_USE::InternalSwap(S_ITEM_USE* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.success_, other->_impl_.success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata S_ITEM_USE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[4]);
}

// ===================================================================

class InventoryRequestPacket::_Internal {
 public:
};

InventoryRequestPacket::InventoryRequestPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.InventoryRequestPacket)
}
InventoryRequestPacket::InventoryRequestPacket(const InventoryRequestPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InventoryRequestPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.userseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.userseq_ = from._impl_.userseq_;
  // @@protoc_insertion_point(copy_constructor:Protocol.InventoryRequestPacket)
}

inline void InventoryRequestPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.userseq_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InventoryRequestPacket::~InventoryRequestPacket() {
  // @@protoc_insertion_point(destructor:Protocol.InventoryRequestPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InventoryRequestPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InventoryRequestPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InventoryRequestPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.InventoryRequestPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userseq_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InventoryRequestPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 userSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InventoryRequestPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.InventoryRequestPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_userseq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.InventoryRequestPacket)
  return target;
}

size_t InventoryRequestPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.InventoryRequestPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_userseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InventoryRequestPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InventoryRequestPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InventoryRequestPacket::GetClassData() const { return &_class_data_; }


void InventoryRequestPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InventoryRequestPacket*>(&to_msg);
  auto& from = static_cast<const InventoryRequestPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.InventoryRequestPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InventoryRequestPacket::CopyFrom(const InventoryRequestPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.InventoryRequestPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InventoryRequestPacket::IsInitialized() const {
  return true;
}

void InventoryRequestPacket::InternalSwap(InventoryRequestPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.userseq_, other->_impl_.userseq_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InventoryRequestPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[5]);
}

// ===================================================================

class InventoryResponsePacket::_Internal {
 public:
};

void InventoryResponsePacket::clear_items() {
  _impl_.items_.Clear();
}
InventoryResponsePacket::InventoryResponsePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.InventoryResponsePacket)
}
InventoryResponsePacket::InventoryResponsePacket(const InventoryResponsePacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InventoryResponsePacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){from._impl_.items_}
    , decltype(_impl_.userseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.userseq_ = from._impl_.userseq_;
  // @@protoc_insertion_point(copy_constructor:Protocol.InventoryResponsePacket)
}

inline void InventoryResponsePacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){arena}
    , decltype(_impl_.userseq_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InventoryResponsePacket::~InventoryResponsePacket() {
  // @@protoc_insertion_point(destructor:Protocol.InventoryResponsePacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InventoryResponsePacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.items_.~RepeatedPtrField();
}

void InventoryResponsePacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InventoryResponsePacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.InventoryResponsePacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  _impl_.userseq_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InventoryResponsePacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 userSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.userseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .Protocol.Item items = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_items(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InventoryResponsePacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.InventoryResponsePacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_userseq(), target);
  }

  // repeated .Protocol.Item items = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_items(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.InventoryResponsePacket)
  return target;
}

size_t InventoryResponsePacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.InventoryResponsePacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Protocol.Item items = 2;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->_impl_.items_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 userSeq = 1;
  if (this->_internal_userseq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_userseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InventoryResponsePacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InventoryResponsePacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InventoryResponsePacket::GetClassData() const { return &_class_data_; }


void InventoryResponsePacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InventoryResponsePacket*>(&to_msg);
  auto& from = static_cast<const InventoryResponsePacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.InventoryResponsePacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.items_.MergeFrom(from._impl_.items_);
  if (from._internal_userseq() != 0) {
    _this->_internal_set_userseq(from._internal_userseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InventoryResponsePacket::CopyFrom(const InventoryResponsePacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.InventoryResponsePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InventoryResponsePacket::IsInitialized() const {
  return true;
}

void InventoryResponsePacket::InternalSwap(InventoryResponsePacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
  swap(_impl_.userseq_, other->_impl_.userseq_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InventoryResponsePacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[6]);
}

// ===================================================================

class LoginRequestPacket::_Internal {
 public:
};

LoginRequestPacket::LoginRequestPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.LoginRequestPacket)
}
LoginRequestPacket::LoginRequestPacket(const LoginRequestPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LoginRequestPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.playerid_){}
    , decltype(_impl_.playerseq_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.playerid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.playerid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_playerid().empty()) {
    _this->_impl_.playerid_.Set(from._internal_playerid(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.playerseq_ = from._impl_.playerseq_;
  // @@protoc_insertion_point(copy_constructor:Protocol.LoginRequestPacket)
}

inline void LoginRequestPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.playerid_){}
    , decltype(_impl_.playerseq_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.playerid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.playerid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LoginRequestPacket::~LoginRequestPacket() {
  // @@protoc_insertion_point(destructor:Protocol.LoginRequestPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LoginRequestPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.playerid_.Destroy();
}

void LoginRequestPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LoginRequestPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.LoginRequestPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.playerid_.ClearToEmpty();
  _impl_.playerseq_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LoginRequestPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 playerSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.playerseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string playerId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_playerid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.LoginRequestPacket.playerId"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LoginRequestPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.LoginRequestPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 playerSeq = 1;
  if (this->_internal_playerseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_playerseq(), target);
  }

  // string playerId = 2;
  if (!this->_internal_playerid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_playerid().data(), static_cast<int>(this->_internal_playerid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.LoginRequestPacket.playerId");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_playerid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.LoginRequestPacket)
  return target;
}

size_t LoginRequestPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.LoginRequestPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string playerId = 2;
  if (!this->_internal_playerid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_playerid());
  }

  // uint32 playerSeq = 1;
  if (this->_internal_playerseq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_playerseq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LoginRequestPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LoginRequestPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LoginRequestPacket::GetClassData() const { return &_class_data_; }


void LoginRequestPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LoginRequestPacket*>(&to_msg);
  auto& from = static_cast<const LoginRequestPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.LoginRequestPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_playerid().empty()) {
    _this->_internal_set_playerid(from._internal_playerid());
  }
  if (from._internal_playerseq() != 0) {
    _this->_internal_set_playerseq(from._internal_playerseq());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LoginRequestPacket::CopyFrom(const LoginRequestPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.LoginRequestPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginRequestPacket::IsInitialized() const {
  return true;
}

void LoginRequestPacket::InternalSwap(LoginRequestPacket* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.playerid_, lhs_arena,
      &other->_impl_.playerid_, rhs_arena
  );
  swap(_impl_.playerseq_, other->_impl_.playerseq_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LoginRequestPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[7]);
}

// ===================================================================

class LoginResponsePacket::_Internal {
 public:
};

LoginResponsePacket::LoginResponsePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.LoginResponsePacket)
}
LoginResponsePacket::LoginResponsePacket(const LoginResponsePacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LoginResponsePacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.gameserveraddress_){}
    , decltype(_impl_.playerseq_){}
    , decltype(_impl_.success_){}
    , decltype(_impl_.gameserverport_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.gameserveraddress_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.gameserveraddress_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_gameserveraddress().empty()) {
    _this->_impl_.gameserveraddress_.Set(from._internal_gameserveraddress(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.playerseq_, &from._impl_.playerseq_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.gameserverport_) -
    reinterpret_cast<char*>(&_impl_.playerseq_)) + sizeof(_impl_.gameserverport_));
  // @@protoc_insertion_point(copy_constructor:Protocol.LoginResponsePacket)
}

inline void LoginResponsePacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.gameserveraddress_){}
    , decltype(_impl_.playerseq_){0u}
    , decltype(_impl_.success_){false}
    , decltype(_impl_.gameserverport_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.gameserveraddress_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.gameserveraddress_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LoginResponsePacket::~LoginResponsePacket() {
  // @@protoc_insertion_point(destructor:Protocol.LoginResponsePacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LoginResponsePacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.gameserveraddress_.Destroy();
}

void LoginResponsePacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LoginResponsePacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.LoginResponsePacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.gameserveraddress_.ClearToEmpty();
  ::memset(&_impl_.playerseq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.gameserverport_) -
      reinterpret_cast<char*>(&_impl_.playerseq_)) + sizeof(_impl_.gameserverport_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LoginResponsePacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 playerSeq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.playerseq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool success = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr) > 0 ? 1 : 0;
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string gameServerAddress = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_gameserveraddress();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.LoginResponsePacket.gameServerAddress"));
        } else
          goto handle_unusual;
        continue;
      // int32 gameServerPort = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.gameserverport_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LoginResponsePacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.LoginResponsePacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 playerSeq = 1;
  if (this->_internal_playerseq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_playerseq(), target);
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_success(), target);
  }

  // string gameServerAddress = 3;
  if (!this->_internal_gameserveraddress().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_gameserveraddress().data(), static_cast<int>(this->_internal_gameserveraddress().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.LoginResponsePacket.gameServerAddress");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_gameserveraddress(), target);
  }

  // int32 gameServerPort = 4;
  if (this->_internal_gameserverport() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_gameserverport(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.LoginResponsePacket)
  return target;
}

size_t LoginResponsePacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.LoginResponsePacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string gameServerAddress = 3;
  if (!this->_internal_gameserveraddress().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_gameserveraddress());
  }

  // uint32 playerSeq = 1;
  if (this->_internal_playerseq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_playerseq());
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  // int32 gameServerPort = 4;
  if (this->_internal_gameserverport() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_gameserverport());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LoginResponsePacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LoginResponsePacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LoginResponsePacket::GetClassData() const { return &_class_data_; }


void LoginResponsePacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LoginResponsePacket*>(&to_msg);
  auto& from = static_cast<const LoginResponsePacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.LoginResponsePacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_gameserveraddress().empty()) {
    _this->_internal_set_gameserveraddress(from._internal_gameserveraddress());
  }
  if (from._internal_playerseq() != 0) {
    _this->_internal_set_playerseq(from._internal_playerseq());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  if (from._internal_gameserverport() != 0) {
    _this->_internal_set_gameserverport(from._internal_gameserverport());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LoginResponsePacket::CopyFrom(const LoginResponsePacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.LoginResponsePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginResponsePacket::IsInitialized() const {
  return true;
}

void LoginResponsePacket::InternalSwap(LoginResponsePacket* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.gameserveraddress_, lhs_arena,
      &other->_impl_.gameserveraddress_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LoginResponsePacket, _impl_.gameserverport_)
      + sizeof(LoginResponsePacket::_impl_.gameserverport_)
      - PROTOBUF_FIELD_OFFSET(LoginResponsePacket, _impl_.playerseq_)>(
          reinterpret_cast<char*>(&_impl_.playerseq_),
          reinterpret_cast<char*>(&other->_impl_.playerseq_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LoginResponsePacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_2eproto_getter, &descriptor_table_Packet_2eproto_once,
      file_level_metadata_Packet_2eproto[8]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::PacketHeader*
Arena::CreateMaybeMessage< ::Protocol::PacketHeader >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::PacketHeader >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C_ITEM_ADD*
Arena::CreateMaybeMessage< ::Protocol::C_ITEM_ADD >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_ITEM_ADD >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_ITEM_ADD*
Arena::CreateMaybeMessage< ::Protocol::S_ITEM_ADD >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_ITEM_ADD >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C_ITEM_USE*
Arena::CreateMaybeMessage< ::Protocol::C_ITEM_USE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_ITEM_USE >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_ITEM_USE*
Arena::CreateMaybeMessage< ::Protocol::S_ITEM_USE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_ITEM_USE >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::InventoryRequestPacket*
Arena::CreateMaybeMessage< ::Protocol::InventoryRequestPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::InventoryRequestPacket >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::InventoryResponsePacket*
Arena::CreateMaybeMessage< ::Protocol::InventoryResponsePacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::InventoryResponsePacket >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::LoginRequestPacket*
Arena::CreateMaybeMessage< ::Protocol::LoginRequestPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::LoginRequestPacket >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::LoginResponsePacket*
Arena::CreateMaybeMessage< ::Protocol::LoginResponsePacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::LoginResponsePacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
