// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Packet_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Packet_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Packet_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Packet_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Packet_2eproto;
namespace Protocol {
class C_ITEM_ADD;
struct C_ITEM_ADDDefaultTypeInternal;
extern C_ITEM_ADDDefaultTypeInternal _C_ITEM_ADD_default_instance_;
class C_ITEM_USE;
struct C_ITEM_USEDefaultTypeInternal;
extern C_ITEM_USEDefaultTypeInternal _C_ITEM_USE_default_instance_;
class InventoryRequestPacket;
struct InventoryRequestPacketDefaultTypeInternal;
extern InventoryRequestPacketDefaultTypeInternal _InventoryRequestPacket_default_instance_;
class InventoryResponsePacket;
struct InventoryResponsePacketDefaultTypeInternal;
extern InventoryResponsePacketDefaultTypeInternal _InventoryResponsePacket_default_instance_;
class LoginRequestPacket;
struct LoginRequestPacketDefaultTypeInternal;
extern LoginRequestPacketDefaultTypeInternal _LoginRequestPacket_default_instance_;
class LoginResponsePacket;
struct LoginResponsePacketDefaultTypeInternal;
extern LoginResponsePacketDefaultTypeInternal _LoginResponsePacket_default_instance_;
class PacketHeader;
struct PacketHeaderDefaultTypeInternal;
extern PacketHeaderDefaultTypeInternal _PacketHeader_default_instance_;
class S_ITEM_ADD;
struct S_ITEM_ADDDefaultTypeInternal;
extern S_ITEM_ADDDefaultTypeInternal _S_ITEM_ADD_default_instance_;
class S_ITEM_USE;
struct S_ITEM_USEDefaultTypeInternal;
extern S_ITEM_USEDefaultTypeInternal _S_ITEM_USE_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_ITEM_ADD* Arena::CreateMaybeMessage<::Protocol::C_ITEM_ADD>(Arena*);
template<> ::Protocol::C_ITEM_USE* Arena::CreateMaybeMessage<::Protocol::C_ITEM_USE>(Arena*);
template<> ::Protocol::InventoryRequestPacket* Arena::CreateMaybeMessage<::Protocol::InventoryRequestPacket>(Arena*);
template<> ::Protocol::InventoryResponsePacket* Arena::CreateMaybeMessage<::Protocol::InventoryResponsePacket>(Arena*);
template<> ::Protocol::LoginRequestPacket* Arena::CreateMaybeMessage<::Protocol::LoginRequestPacket>(Arena*);
template<> ::Protocol::LoginResponsePacket* Arena::CreateMaybeMessage<::Protocol::LoginResponsePacket>(Arena*);
template<> ::Protocol::PacketHeader* Arena::CreateMaybeMessage<::Protocol::PacketHeader>(Arena*);
template<> ::Protocol::S_ITEM_ADD* Arena::CreateMaybeMessage<::Protocol::S_ITEM_ADD>(Arena*);
template<> ::Protocol::S_ITEM_USE* Arena::CreateMaybeMessage<::Protocol::S_ITEM_USE>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class PacketHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PacketHeader) */ {
 public:
  inline PacketHeader() : PacketHeader(nullptr) {}
  ~PacketHeader() override;
  explicit PROTOBUF_CONSTEXPR PacketHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PacketHeader(const PacketHeader& from);
  PacketHeader(PacketHeader&& from) noexcept
    : PacketHeader() {
    *this = ::std::move(from);
  }

  inline PacketHeader& operator=(const PacketHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline PacketHeader& operator=(PacketHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PacketHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const PacketHeader* internal_default_instance() {
    return reinterpret_cast<const PacketHeader*>(
               &_PacketHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PacketHeader& a, PacketHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(PacketHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PacketHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PacketHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PacketHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PacketHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PacketHeader& from) {
    PacketHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PacketHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PacketHeader";
  }
  protected:
  explicit PacketHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
  };
  // int32 type = 1;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PacketHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class C_ITEM_ADD final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_ITEM_ADD) */ {
 public:
  inline C_ITEM_ADD() : C_ITEM_ADD(nullptr) {}
  ~C_ITEM_ADD() override;
  explicit PROTOBUF_CONSTEXPR C_ITEM_ADD(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ITEM_ADD(const C_ITEM_ADD& from);
  C_ITEM_ADD(C_ITEM_ADD&& from) noexcept
    : C_ITEM_ADD() {
    *this = ::std::move(from);
  }

  inline C_ITEM_ADD& operator=(const C_ITEM_ADD& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ITEM_ADD& operator=(C_ITEM_ADD&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ITEM_ADD& default_instance() {
    return *internal_default_instance();
  }
  enum ItemDataCase {
    kEquip = 3,
    kConsumption = 4,
    kEtc = 5,
    ITEM_DATA_NOT_SET = 0,
  };

  static inline const C_ITEM_ADD* internal_default_instance() {
    return reinterpret_cast<const C_ITEM_ADD*>(
               &_C_ITEM_ADD_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(C_ITEM_ADD& a, C_ITEM_ADD& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ITEM_ADD* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ITEM_ADD* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_ITEM_ADD* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_ITEM_ADD>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_ITEM_ADD& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_ITEM_ADD& from) {
    C_ITEM_ADD::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_ITEM_ADD* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_ITEM_ADD";
  }
  protected:
  explicit C_ITEM_ADD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemFieldNumber = 2,
    kUserSeqFieldNumber = 1,
    kEquipFieldNumber = 3,
    kConsumptionFieldNumber = 4,
    kEtcFieldNumber = 5,
  };
  // .Protocol.Item item = 2;
  bool has_item() const;
  private:
  bool _internal_has_item() const;
  public:
  void clear_item();
  const ::Protocol::Item& item() const;
  PROTOBUF_NODISCARD ::Protocol::Item* release_item();
  ::Protocol::Item* mutable_item();
  void set_allocated_item(::Protocol::Item* item);
  private:
  const ::Protocol::Item& _internal_item() const;
  ::Protocol::Item* _internal_mutable_item();
  public:
  void unsafe_arena_set_allocated_item(
      ::Protocol::Item* item);
  ::Protocol::Item* unsafe_arena_release_item();

  // uint32 userSeq = 1;
  void clear_userseq();
  uint32_t userseq() const;
  void set_userseq(uint32_t value);
  private:
  uint32_t _internal_userseq() const;
  void _internal_set_userseq(uint32_t value);
  public:

  // .Protocol.Equip equip = 3;
  bool has_equip() const;
  private:
  bool _internal_has_equip() const;
  public:
  void clear_equip();
  const ::Protocol::Equip& equip() const;
  PROTOBUF_NODISCARD ::Protocol::Equip* release_equip();
  ::Protocol::Equip* mutable_equip();
  void set_allocated_equip(::Protocol::Equip* equip);
  private:
  const ::Protocol::Equip& _internal_equip() const;
  ::Protocol::Equip* _internal_mutable_equip();
  public:
  void unsafe_arena_set_allocated_equip(
      ::Protocol::Equip* equip);
  ::Protocol::Equip* unsafe_arena_release_equip();

  // .Protocol.Consumption consumption = 4;
  bool has_consumption() const;
  private:
  bool _internal_has_consumption() const;
  public:
  void clear_consumption();
  const ::Protocol::Consumption& consumption() const;
  PROTOBUF_NODISCARD ::Protocol::Consumption* release_consumption();
  ::Protocol::Consumption* mutable_consumption();
  void set_allocated_consumption(::Protocol::Consumption* consumption);
  private:
  const ::Protocol::Consumption& _internal_consumption() const;
  ::Protocol::Consumption* _internal_mutable_consumption();
  public:
  void unsafe_arena_set_allocated_consumption(
      ::Protocol::Consumption* consumption);
  ::Protocol::Consumption* unsafe_arena_release_consumption();

  // .Protocol.EtcItem etc = 5;
  bool has_etc() const;
  private:
  bool _internal_has_etc() const;
  public:
  void clear_etc();
  const ::Protocol::EtcItem& etc() const;
  PROTOBUF_NODISCARD ::Protocol::EtcItem* release_etc();
  ::Protocol::EtcItem* mutable_etc();
  void set_allocated_etc(::Protocol::EtcItem* etc);
  private:
  const ::Protocol::EtcItem& _internal_etc() const;
  ::Protocol::EtcItem* _internal_mutable_etc();
  public:
  void unsafe_arena_set_allocated_etc(
      ::Protocol::EtcItem* etc);
  ::Protocol::EtcItem* unsafe_arena_release_etc();

  void clear_item_data();
  ItemDataCase item_data_case() const;
  // @@protoc_insertion_point(class_scope:Protocol.C_ITEM_ADD)
 private:
  class _Internal;
  void set_has_equip();
  void set_has_consumption();
  void set_has_etc();

  inline bool has_item_data() const;
  inline void clear_has_item_data();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Item* item_;
    uint32_t userseq_;
    union ItemDataUnion {
      constexpr ItemDataUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::Protocol::Equip* equip_;
      ::Protocol::Consumption* consumption_;
      ::Protocol::EtcItem* etc_;
    } item_data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class S_ITEM_ADD final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_ITEM_ADD) */ {
 public:
  inline S_ITEM_ADD() : S_ITEM_ADD(nullptr) {}
  ~S_ITEM_ADD() override;
  explicit PROTOBUF_CONSTEXPR S_ITEM_ADD(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_ITEM_ADD(const S_ITEM_ADD& from);
  S_ITEM_ADD(S_ITEM_ADD&& from) noexcept
    : S_ITEM_ADD() {
    *this = ::std::move(from);
  }

  inline S_ITEM_ADD& operator=(const S_ITEM_ADD& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_ITEM_ADD& operator=(S_ITEM_ADD&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_ITEM_ADD& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_ITEM_ADD* internal_default_instance() {
    return reinterpret_cast<const S_ITEM_ADD*>(
               &_S_ITEM_ADD_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(S_ITEM_ADD& a, S_ITEM_ADD& b) {
    a.Swap(&b);
  }
  inline void Swap(S_ITEM_ADD* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_ITEM_ADD* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_ITEM_ADD* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_ITEM_ADD>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_ITEM_ADD& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_ITEM_ADD& from) {
    S_ITEM_ADD::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_ITEM_ADD* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_ITEM_ADD";
  }
  protected:
  explicit S_ITEM_ADD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_ITEM_ADD)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class C_ITEM_USE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_ITEM_USE) */ {
 public:
  inline C_ITEM_USE() : C_ITEM_USE(nullptr) {}
  ~C_ITEM_USE() override;
  explicit PROTOBUF_CONSTEXPR C_ITEM_USE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ITEM_USE(const C_ITEM_USE& from);
  C_ITEM_USE(C_ITEM_USE&& from) noexcept
    : C_ITEM_USE() {
    *this = ::std::move(from);
  }

  inline C_ITEM_USE& operator=(const C_ITEM_USE& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ITEM_USE& operator=(C_ITEM_USE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ITEM_USE& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ITEM_USE* internal_default_instance() {
    return reinterpret_cast<const C_ITEM_USE*>(
               &_C_ITEM_USE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(C_ITEM_USE& a, C_ITEM_USE& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ITEM_USE* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ITEM_USE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_ITEM_USE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_ITEM_USE>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_ITEM_USE& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_ITEM_USE& from) {
    C_ITEM_USE::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_ITEM_USE* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_ITEM_USE";
  }
  protected:
  explicit C_ITEM_USE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserSeqFieldNumber = 1,
    kItemSeqFieldNumber = 2,
  };
  // uint32 userSeq = 1;
  void clear_userseq();
  uint32_t userseq() const;
  void set_userseq(uint32_t value);
  private:
  uint32_t _internal_userseq() const;
  void _internal_set_userseq(uint32_t value);
  public:

  // int32 itemSeq = 2;
  void clear_itemseq();
  int32_t itemseq() const;
  void set_itemseq(int32_t value);
  private:
  int32_t _internal_itemseq() const;
  void _internal_set_itemseq(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_ITEM_USE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t userseq_;
    int32_t itemseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class S_ITEM_USE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_ITEM_USE) */ {
 public:
  inline S_ITEM_USE() : S_ITEM_USE(nullptr) {}
  ~S_ITEM_USE() override;
  explicit PROTOBUF_CONSTEXPR S_ITEM_USE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_ITEM_USE(const S_ITEM_USE& from);
  S_ITEM_USE(S_ITEM_USE&& from) noexcept
    : S_ITEM_USE() {
    *this = ::std::move(from);
  }

  inline S_ITEM_USE& operator=(const S_ITEM_USE& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_ITEM_USE& operator=(S_ITEM_USE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_ITEM_USE& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_ITEM_USE* internal_default_instance() {
    return reinterpret_cast<const S_ITEM_USE*>(
               &_S_ITEM_USE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(S_ITEM_USE& a, S_ITEM_USE& b) {
    a.Swap(&b);
  }
  inline void Swap(S_ITEM_USE* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_ITEM_USE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_ITEM_USE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_ITEM_USE>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_ITEM_USE& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_ITEM_USE& from) {
    S_ITEM_USE::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_ITEM_USE* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_ITEM_USE";
  }
  protected:
  explicit S_ITEM_USE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_ITEM_USE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class InventoryRequestPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.InventoryRequestPacket) */ {
 public:
  inline InventoryRequestPacket() : InventoryRequestPacket(nullptr) {}
  ~InventoryRequestPacket() override;
  explicit PROTOBUF_CONSTEXPR InventoryRequestPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InventoryRequestPacket(const InventoryRequestPacket& from);
  InventoryRequestPacket(InventoryRequestPacket&& from) noexcept
    : InventoryRequestPacket() {
    *this = ::std::move(from);
  }

  inline InventoryRequestPacket& operator=(const InventoryRequestPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline InventoryRequestPacket& operator=(InventoryRequestPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InventoryRequestPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const InventoryRequestPacket* internal_default_instance() {
    return reinterpret_cast<const InventoryRequestPacket*>(
               &_InventoryRequestPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(InventoryRequestPacket& a, InventoryRequestPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(InventoryRequestPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InventoryRequestPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InventoryRequestPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InventoryRequestPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InventoryRequestPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InventoryRequestPacket& from) {
    InventoryRequestPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InventoryRequestPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.InventoryRequestPacket";
  }
  protected:
  explicit InventoryRequestPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserSeqFieldNumber = 1,
  };
  // uint32 userSeq = 1;
  void clear_userseq();
  uint32_t userseq() const;
  void set_userseq(uint32_t value);
  private:
  uint32_t _internal_userseq() const;
  void _internal_set_userseq(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.InventoryRequestPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class InventoryResponsePacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.InventoryResponsePacket) */ {
 public:
  inline InventoryResponsePacket() : InventoryResponsePacket(nullptr) {}
  ~InventoryResponsePacket() override;
  explicit PROTOBUF_CONSTEXPR InventoryResponsePacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InventoryResponsePacket(const InventoryResponsePacket& from);
  InventoryResponsePacket(InventoryResponsePacket&& from) noexcept
    : InventoryResponsePacket() {
    *this = ::std::move(from);
  }

  inline InventoryResponsePacket& operator=(const InventoryResponsePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline InventoryResponsePacket& operator=(InventoryResponsePacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InventoryResponsePacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const InventoryResponsePacket* internal_default_instance() {
    return reinterpret_cast<const InventoryResponsePacket*>(
               &_InventoryResponsePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(InventoryResponsePacket& a, InventoryResponsePacket& b) {
    a.Swap(&b);
  }
  inline void Swap(InventoryResponsePacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InventoryResponsePacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InventoryResponsePacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InventoryResponsePacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InventoryResponsePacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InventoryResponsePacket& from) {
    InventoryResponsePacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InventoryResponsePacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.InventoryResponsePacket";
  }
  protected:
  explicit InventoryResponsePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 2,
    kUserSeqFieldNumber = 1,
  };
  // repeated .Protocol.Item items = 2;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::Protocol::Item* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item >*
      mutable_items();
  private:
  const ::Protocol::Item& _internal_items(int index) const;
  ::Protocol::Item* _internal_add_items();
  public:
  const ::Protocol::Item& items(int index) const;
  ::Protocol::Item* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item >&
      items() const;

  // uint32 userSeq = 1;
  void clear_userseq();
  uint32_t userseq() const;
  void set_userseq(uint32_t value);
  private:
  uint32_t _internal_userseq() const;
  void _internal_set_userseq(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.InventoryResponsePacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item > items_;
    uint32_t userseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class LoginRequestPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.LoginRequestPacket) */ {
 public:
  inline LoginRequestPacket() : LoginRequestPacket(nullptr) {}
  ~LoginRequestPacket() override;
  explicit PROTOBUF_CONSTEXPR LoginRequestPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginRequestPacket(const LoginRequestPacket& from);
  LoginRequestPacket(LoginRequestPacket&& from) noexcept
    : LoginRequestPacket() {
    *this = ::std::move(from);
  }

  inline LoginRequestPacket& operator=(const LoginRequestPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginRequestPacket& operator=(LoginRequestPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginRequestPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginRequestPacket* internal_default_instance() {
    return reinterpret_cast<const LoginRequestPacket*>(
               &_LoginRequestPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(LoginRequestPacket& a, LoginRequestPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginRequestPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginRequestPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginRequestPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginRequestPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginRequestPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginRequestPacket& from) {
    LoginRequestPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginRequestPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.LoginRequestPacket";
  }
  protected:
  explicit LoginRequestPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 2,
    kPlayerSeqFieldNumber = 1,
  };
  // string playerId = 2;
  void clear_playerid();
  const std::string& playerid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_playerid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_playerid();
  PROTOBUF_NODISCARD std::string* release_playerid();
  void set_allocated_playerid(std::string* playerid);
  private:
  const std::string& _internal_playerid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_playerid(const std::string& value);
  std::string* _internal_mutable_playerid();
  public:

  // uint32 playerSeq = 1;
  void clear_playerseq();
  uint32_t playerseq() const;
  void set_playerseq(uint32_t value);
  private:
  uint32_t _internal_playerseq() const;
  void _internal_set_playerseq(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.LoginRequestPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr playerid_;
    uint32_t playerseq_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class LoginResponsePacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.LoginResponsePacket) */ {
 public:
  inline LoginResponsePacket() : LoginResponsePacket(nullptr) {}
  ~LoginResponsePacket() override;
  explicit PROTOBUF_CONSTEXPR LoginResponsePacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginResponsePacket(const LoginResponsePacket& from);
  LoginResponsePacket(LoginResponsePacket&& from) noexcept
    : LoginResponsePacket() {
    *this = ::std::move(from);
  }

  inline LoginResponsePacket& operator=(const LoginResponsePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginResponsePacket& operator=(LoginResponsePacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginResponsePacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginResponsePacket* internal_default_instance() {
    return reinterpret_cast<const LoginResponsePacket*>(
               &_LoginResponsePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(LoginResponsePacket& a, LoginResponsePacket& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginResponsePacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginResponsePacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginResponsePacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginResponsePacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginResponsePacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginResponsePacket& from) {
    LoginResponsePacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginResponsePacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.LoginResponsePacket";
  }
  protected:
  explicit LoginResponsePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGameServerAddressFieldNumber = 3,
    kPlayerSeqFieldNumber = 1,
    kSuccessFieldNumber = 2,
    kGameServerPortFieldNumber = 4,
  };
  // string gameServerAddress = 3;
  void clear_gameserveraddress();
  const std::string& gameserveraddress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_gameserveraddress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_gameserveraddress();
  PROTOBUF_NODISCARD std::string* release_gameserveraddress();
  void set_allocated_gameserveraddress(std::string* gameserveraddress);
  private:
  const std::string& _internal_gameserveraddress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_gameserveraddress(const std::string& value);
  std::string* _internal_mutable_gameserveraddress();
  public:

  // uint32 playerSeq = 1;
  void clear_playerseq();
  uint32_t playerseq() const;
  void set_playerseq(uint32_t value);
  private:
  uint32_t _internal_playerseq() const;
  void _internal_set_playerseq(uint32_t value);
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 gameServerPort = 4;
  void clear_gameserverport();
  int32_t gameserverport() const;
  void set_gameserverport(int32_t value);
  private:
  int32_t _internal_gameserverport() const;
  void _internal_set_gameserverport(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.LoginResponsePacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gameserveraddress_;
    uint32_t playerseq_;
    bool success_;
    int32_t gameserverport_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PacketHeader

// int32 type = 1;
inline void PacketHeader::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t PacketHeader::_internal_type() const {
  return _impl_.type_;
}
inline int32_t PacketHeader::type() const {
  // @@protoc_insertion_point(field_get:Protocol.PacketHeader.type)
  return _internal_type();
}
inline void PacketHeader::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void PacketHeader::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Protocol.PacketHeader.type)
}

// -------------------------------------------------------------------

// C_ITEM_ADD

// uint32 userSeq = 1;
inline void C_ITEM_ADD::clear_userseq() {
  _impl_.userseq_ = 0u;
}
inline uint32_t C_ITEM_ADD::_internal_userseq() const {
  return _impl_.userseq_;
}
inline uint32_t C_ITEM_ADD::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ITEM_ADD.userSeq)
  return _internal_userseq();
}
inline void C_ITEM_ADD::_internal_set_userseq(uint32_t value) {
  
  _impl_.userseq_ = value;
}
inline void C_ITEM_ADD::set_userseq(uint32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.C_ITEM_ADD.userSeq)
}

// .Protocol.Item item = 2;
inline bool C_ITEM_ADD::_internal_has_item() const {
  return this != internal_default_instance() && _impl_.item_ != nullptr;
}
inline bool C_ITEM_ADD::has_item() const {
  return _internal_has_item();
}
inline const ::Protocol::Item& C_ITEM_ADD::_internal_item() const {
  const ::Protocol::Item* p = _impl_.item_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Item&>(
      ::Protocol::_Item_default_instance_);
}
inline const ::Protocol::Item& C_ITEM_ADD::item() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ITEM_ADD.item)
  return _internal_item();
}
inline void C_ITEM_ADD::unsafe_arena_set_allocated_item(
    ::Protocol::Item* item) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.item_);
  }
  _impl_.item_ = item;
  if (item) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_ITEM_ADD.item)
}
inline ::Protocol::Item* C_ITEM_ADD::release_item() {
  
  ::Protocol::Item* temp = _impl_.item_;
  _impl_.item_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Item* C_ITEM_ADD::unsafe_arena_release_item() {
  // @@protoc_insertion_point(field_release:Protocol.C_ITEM_ADD.item)
  
  ::Protocol::Item* temp = _impl_.item_;
  _impl_.item_ = nullptr;
  return temp;
}
inline ::Protocol::Item* C_ITEM_ADD::_internal_mutable_item() {
  
  if (_impl_.item_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Item>(GetArenaForAllocation());
    _impl_.item_ = p;
  }
  return _impl_.item_;
}
inline ::Protocol::Item* C_ITEM_ADD::mutable_item() {
  ::Protocol::Item* _msg = _internal_mutable_item();
  // @@protoc_insertion_point(field_mutable:Protocol.C_ITEM_ADD.item)
  return _msg;
}
inline void C_ITEM_ADD::set_allocated_item(::Protocol::Item* item) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.item_);
  }
  if (item) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(item));
    if (message_arena != submessage_arena) {
      item = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, item, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.item_ = item;
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_ITEM_ADD.item)
}

// .Protocol.Equip equip = 3;
inline bool C_ITEM_ADD::_internal_has_equip() const {
  return item_data_case() == kEquip;
}
inline bool C_ITEM_ADD::has_equip() const {
  return _internal_has_equip();
}
inline void C_ITEM_ADD::set_has_equip() {
  _impl_._oneof_case_[0] = kEquip;
}
inline ::Protocol::Equip* C_ITEM_ADD::release_equip() {
  // @@protoc_insertion_point(field_release:Protocol.C_ITEM_ADD.equip)
  if (_internal_has_equip()) {
    clear_has_item_data();
    ::Protocol::Equip* temp = _impl_.item_data_.equip_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.item_data_.equip_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Protocol::Equip& C_ITEM_ADD::_internal_equip() const {
  return _internal_has_equip()
      ? *_impl_.item_data_.equip_
      : reinterpret_cast< ::Protocol::Equip&>(::Protocol::_Equip_default_instance_);
}
inline const ::Protocol::Equip& C_ITEM_ADD::equip() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ITEM_ADD.equip)
  return _internal_equip();
}
inline ::Protocol::Equip* C_ITEM_ADD::unsafe_arena_release_equip() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Protocol.C_ITEM_ADD.equip)
  if (_internal_has_equip()) {
    clear_has_item_data();
    ::Protocol::Equip* temp = _impl_.item_data_.equip_;
    _impl_.item_data_.equip_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void C_ITEM_ADD::unsafe_arena_set_allocated_equip(::Protocol::Equip* equip) {
  clear_item_data();
  if (equip) {
    set_has_equip();
    _impl_.item_data_.equip_ = equip;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_ITEM_ADD.equip)
}
inline ::Protocol::Equip* C_ITEM_ADD::_internal_mutable_equip() {
  if (!_internal_has_equip()) {
    clear_item_data();
    set_has_equip();
    _impl_.item_data_.equip_ = CreateMaybeMessage< ::Protocol::Equip >(GetArenaForAllocation());
  }
  return _impl_.item_data_.equip_;
}
inline ::Protocol::Equip* C_ITEM_ADD::mutable_equip() {
  ::Protocol::Equip* _msg = _internal_mutable_equip();
  // @@protoc_insertion_point(field_mutable:Protocol.C_ITEM_ADD.equip)
  return _msg;
}

// .Protocol.Consumption consumption = 4;
inline bool C_ITEM_ADD::_internal_has_consumption() const {
  return item_data_case() == kConsumption;
}
inline bool C_ITEM_ADD::has_consumption() const {
  return _internal_has_consumption();
}
inline void C_ITEM_ADD::set_has_consumption() {
  _impl_._oneof_case_[0] = kConsumption;
}
inline ::Protocol::Consumption* C_ITEM_ADD::release_consumption() {
  // @@protoc_insertion_point(field_release:Protocol.C_ITEM_ADD.consumption)
  if (_internal_has_consumption()) {
    clear_has_item_data();
    ::Protocol::Consumption* temp = _impl_.item_data_.consumption_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.item_data_.consumption_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Protocol::Consumption& C_ITEM_ADD::_internal_consumption() const {
  return _internal_has_consumption()
      ? *_impl_.item_data_.consumption_
      : reinterpret_cast< ::Protocol::Consumption&>(::Protocol::_Consumption_default_instance_);
}
inline const ::Protocol::Consumption& C_ITEM_ADD::consumption() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ITEM_ADD.consumption)
  return _internal_consumption();
}
inline ::Protocol::Consumption* C_ITEM_ADD::unsafe_arena_release_consumption() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Protocol.C_ITEM_ADD.consumption)
  if (_internal_has_consumption()) {
    clear_has_item_data();
    ::Protocol::Consumption* temp = _impl_.item_data_.consumption_;
    _impl_.item_data_.consumption_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void C_ITEM_ADD::unsafe_arena_set_allocated_consumption(::Protocol::Consumption* consumption) {
  clear_item_data();
  if (consumption) {
    set_has_consumption();
    _impl_.item_data_.consumption_ = consumption;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_ITEM_ADD.consumption)
}
inline ::Protocol::Consumption* C_ITEM_ADD::_internal_mutable_consumption() {
  if (!_internal_has_consumption()) {
    clear_item_data();
    set_has_consumption();
    _impl_.item_data_.consumption_ = CreateMaybeMessage< ::Protocol::Consumption >(GetArenaForAllocation());
  }
  return _impl_.item_data_.consumption_;
}
inline ::Protocol::Consumption* C_ITEM_ADD::mutable_consumption() {
  ::Protocol::Consumption* _msg = _internal_mutable_consumption();
  // @@protoc_insertion_point(field_mutable:Protocol.C_ITEM_ADD.consumption)
  return _msg;
}

// .Protocol.EtcItem etc = 5;
inline bool C_ITEM_ADD::_internal_has_etc() const {
  return item_data_case() == kEtc;
}
inline bool C_ITEM_ADD::has_etc() const {
  return _internal_has_etc();
}
inline void C_ITEM_ADD::set_has_etc() {
  _impl_._oneof_case_[0] = kEtc;
}
inline ::Protocol::EtcItem* C_ITEM_ADD::release_etc() {
  // @@protoc_insertion_point(field_release:Protocol.C_ITEM_ADD.etc)
  if (_internal_has_etc()) {
    clear_has_item_data();
    ::Protocol::EtcItem* temp = _impl_.item_data_.etc_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.item_data_.etc_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Protocol::EtcItem& C_ITEM_ADD::_internal_etc() const {
  return _internal_has_etc()
      ? *_impl_.item_data_.etc_
      : reinterpret_cast< ::Protocol::EtcItem&>(::Protocol::_EtcItem_default_instance_);
}
inline const ::Protocol::EtcItem& C_ITEM_ADD::etc() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ITEM_ADD.etc)
  return _internal_etc();
}
inline ::Protocol::EtcItem* C_ITEM_ADD::unsafe_arena_release_etc() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Protocol.C_ITEM_ADD.etc)
  if (_internal_has_etc()) {
    clear_has_item_data();
    ::Protocol::EtcItem* temp = _impl_.item_data_.etc_;
    _impl_.item_data_.etc_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void C_ITEM_ADD::unsafe_arena_set_allocated_etc(::Protocol::EtcItem* etc) {
  clear_item_data();
  if (etc) {
    set_has_etc();
    _impl_.item_data_.etc_ = etc;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_ITEM_ADD.etc)
}
inline ::Protocol::EtcItem* C_ITEM_ADD::_internal_mutable_etc() {
  if (!_internal_has_etc()) {
    clear_item_data();
    set_has_etc();
    _impl_.item_data_.etc_ = CreateMaybeMessage< ::Protocol::EtcItem >(GetArenaForAllocation());
  }
  return _impl_.item_data_.etc_;
}
inline ::Protocol::EtcItem* C_ITEM_ADD::mutable_etc() {
  ::Protocol::EtcItem* _msg = _internal_mutable_etc();
  // @@protoc_insertion_point(field_mutable:Protocol.C_ITEM_ADD.etc)
  return _msg;
}

inline bool C_ITEM_ADD::has_item_data() const {
  return item_data_case() != ITEM_DATA_NOT_SET;
}
inline void C_ITEM_ADD::clear_has_item_data() {
  _impl_._oneof_case_[0] = ITEM_DATA_NOT_SET;
}
inline C_ITEM_ADD::ItemDataCase C_ITEM_ADD::item_data_case() const {
  return C_ITEM_ADD::ItemDataCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// S_ITEM_ADD

// bool success = 1;
inline void S_ITEM_ADD::clear_success() {
  _impl_.success_ = false;
}
inline bool S_ITEM_ADD::_internal_success() const {
  return _impl_.success_;
}
inline bool S_ITEM_ADD::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_ITEM_ADD.success)
  return _internal_success();
}
inline void S_ITEM_ADD::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void S_ITEM_ADD::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_ITEM_ADD.success)
}

// -------------------------------------------------------------------

// C_ITEM_USE

// uint32 userSeq = 1;
inline void C_ITEM_USE::clear_userseq() {
  _impl_.userseq_ = 0u;
}
inline uint32_t C_ITEM_USE::_internal_userseq() const {
  return _impl_.userseq_;
}
inline uint32_t C_ITEM_USE::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ITEM_USE.userSeq)
  return _internal_userseq();
}
inline void C_ITEM_USE::_internal_set_userseq(uint32_t value) {
  
  _impl_.userseq_ = value;
}
inline void C_ITEM_USE::set_userseq(uint32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.C_ITEM_USE.userSeq)
}

// int32 itemSeq = 2;
inline void C_ITEM_USE::clear_itemseq() {
  _impl_.itemseq_ = 0;
}
inline int32_t C_ITEM_USE::_internal_itemseq() const {
  return _impl_.itemseq_;
}
inline int32_t C_ITEM_USE::itemseq() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ITEM_USE.itemSeq)
  return _internal_itemseq();
}
inline void C_ITEM_USE::_internal_set_itemseq(int32_t value) {
  
  _impl_.itemseq_ = value;
}
inline void C_ITEM_USE::set_itemseq(int32_t value) {
  _internal_set_itemseq(value);
  // @@protoc_insertion_point(field_set:Protocol.C_ITEM_USE.itemSeq)
}

// -------------------------------------------------------------------

// S_ITEM_USE

// bool success = 1;
inline void S_ITEM_USE::clear_success() {
  _impl_.success_ = false;
}
inline bool S_ITEM_USE::_internal_success() const {
  return _impl_.success_;
}
inline bool S_ITEM_USE::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_ITEM_USE.success)
  return _internal_success();
}
inline void S_ITEM_USE::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void S_ITEM_USE::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_ITEM_USE.success)
}

// -------------------------------------------------------------------

// InventoryRequestPacket

// uint32 userSeq = 1;
inline void InventoryRequestPacket::clear_userseq() {
  _impl_.userseq_ = 0u;
}
inline uint32_t InventoryRequestPacket::_internal_userseq() const {
  return _impl_.userseq_;
}
inline uint32_t InventoryRequestPacket::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.InventoryRequestPacket.userSeq)
  return _internal_userseq();
}
inline void InventoryRequestPacket::_internal_set_userseq(uint32_t value) {
  
  _impl_.userseq_ = value;
}
inline void InventoryRequestPacket::set_userseq(uint32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.InventoryRequestPacket.userSeq)
}

// -------------------------------------------------------------------

// InventoryResponsePacket

// uint32 userSeq = 1;
inline void InventoryResponsePacket::clear_userseq() {
  _impl_.userseq_ = 0u;
}
inline uint32_t InventoryResponsePacket::_internal_userseq() const {
  return _impl_.userseq_;
}
inline uint32_t InventoryResponsePacket::userseq() const {
  // @@protoc_insertion_point(field_get:Protocol.InventoryResponsePacket.userSeq)
  return _internal_userseq();
}
inline void InventoryResponsePacket::_internal_set_userseq(uint32_t value) {
  
  _impl_.userseq_ = value;
}
inline void InventoryResponsePacket::set_userseq(uint32_t value) {
  _internal_set_userseq(value);
  // @@protoc_insertion_point(field_set:Protocol.InventoryResponsePacket.userSeq)
}

// repeated .Protocol.Item items = 2;
inline int InventoryResponsePacket::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int InventoryResponsePacket::items_size() const {
  return _internal_items_size();
}
inline ::Protocol::Item* InventoryResponsePacket::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.InventoryResponsePacket.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item >*
InventoryResponsePacket::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.InventoryResponsePacket.items)
  return &_impl_.items_;
}
inline const ::Protocol::Item& InventoryResponsePacket::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::Protocol::Item& InventoryResponsePacket::items(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.InventoryResponsePacket.items)
  return _internal_items(index);
}
inline ::Protocol::Item* InventoryResponsePacket::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::Protocol::Item* InventoryResponsePacket::add_items() {
  ::Protocol::Item* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:Protocol.InventoryResponsePacket.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item >&
InventoryResponsePacket::items() const {
  // @@protoc_insertion_point(field_list:Protocol.InventoryResponsePacket.items)
  return _impl_.items_;
}

// -------------------------------------------------------------------

// LoginRequestPacket

// uint32 playerSeq = 1;
inline void LoginRequestPacket::clear_playerseq() {
  _impl_.playerseq_ = 0u;
}
inline uint32_t LoginRequestPacket::_internal_playerseq() const {
  return _impl_.playerseq_;
}
inline uint32_t LoginRequestPacket::playerseq() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginRequestPacket.playerSeq)
  return _internal_playerseq();
}
inline void LoginRequestPacket::_internal_set_playerseq(uint32_t value) {
  
  _impl_.playerseq_ = value;
}
inline void LoginRequestPacket::set_playerseq(uint32_t value) {
  _internal_set_playerseq(value);
  // @@protoc_insertion_point(field_set:Protocol.LoginRequestPacket.playerSeq)
}

// string playerId = 2;
inline void LoginRequestPacket::clear_playerid() {
  _impl_.playerid_.ClearToEmpty();
}
inline const std::string& LoginRequestPacket::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginRequestPacket.playerId)
  return _internal_playerid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginRequestPacket::set_playerid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.playerid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.LoginRequestPacket.playerId)
}
inline std::string* LoginRequestPacket::mutable_playerid() {
  std::string* _s = _internal_mutable_playerid();
  // @@protoc_insertion_point(field_mutable:Protocol.LoginRequestPacket.playerId)
  return _s;
}
inline const std::string& LoginRequestPacket::_internal_playerid() const {
  return _impl_.playerid_.Get();
}
inline void LoginRequestPacket::_internal_set_playerid(const std::string& value) {
  
  _impl_.playerid_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRequestPacket::_internal_mutable_playerid() {
  
  return _impl_.playerid_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginRequestPacket::release_playerid() {
  // @@protoc_insertion_point(field_release:Protocol.LoginRequestPacket.playerId)
  return _impl_.playerid_.Release();
}
inline void LoginRequestPacket::set_allocated_playerid(std::string* playerid) {
  if (playerid != nullptr) {
    
  } else {
    
  }
  _impl_.playerid_.SetAllocated(playerid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.playerid_.IsDefault()) {
    _impl_.playerid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.LoginRequestPacket.playerId)
}

// -------------------------------------------------------------------

// LoginResponsePacket

// uint32 playerSeq = 1;
inline void LoginResponsePacket::clear_playerseq() {
  _impl_.playerseq_ = 0u;
}
inline uint32_t LoginResponsePacket::_internal_playerseq() const {
  return _impl_.playerseq_;
}
inline uint32_t LoginResponsePacket::playerseq() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginResponsePacket.playerSeq)
  return _internal_playerseq();
}
inline void LoginResponsePacket::_internal_set_playerseq(uint32_t value) {
  
  _impl_.playerseq_ = value;
}
inline void LoginResponsePacket::set_playerseq(uint32_t value) {
  _internal_set_playerseq(value);
  // @@protoc_insertion_point(field_set:Protocol.LoginResponsePacket.playerSeq)
}

// bool success = 2;
inline void LoginResponsePacket::clear_success() {
  _impl_.success_ = false;
}
inline bool LoginResponsePacket::_internal_success() const {
  return _impl_.success_;
}
inline bool LoginResponsePacket::success() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginResponsePacket.success)
  return _internal_success();
}
inline void LoginResponsePacket::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void LoginResponsePacket::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.LoginResponsePacket.success)
}

// string gameServerAddress = 3;
inline void LoginResponsePacket::clear_gameserveraddress() {
  _impl_.gameserveraddress_.ClearToEmpty();
}
inline const std::string& LoginResponsePacket::gameserveraddress() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginResponsePacket.gameServerAddress)
  return _internal_gameserveraddress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginResponsePacket::set_gameserveraddress(ArgT0&& arg0, ArgT... args) {
 
 _impl_.gameserveraddress_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.LoginResponsePacket.gameServerAddress)
}
inline std::string* LoginResponsePacket::mutable_gameserveraddress() {
  std::string* _s = _internal_mutable_gameserveraddress();
  // @@protoc_insertion_point(field_mutable:Protocol.LoginResponsePacket.gameServerAddress)
  return _s;
}
inline const std::string& LoginResponsePacket::_internal_gameserveraddress() const {
  return _impl_.gameserveraddress_.Get();
}
inline void LoginResponsePacket::_internal_set_gameserveraddress(const std::string& value) {
  
  _impl_.gameserveraddress_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginResponsePacket::_internal_mutable_gameserveraddress() {
  
  return _impl_.gameserveraddress_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginResponsePacket::release_gameserveraddress() {
  // @@protoc_insertion_point(field_release:Protocol.LoginResponsePacket.gameServerAddress)
  return _impl_.gameserveraddress_.Release();
}
inline void LoginResponsePacket::set_allocated_gameserveraddress(std::string* gameserveraddress) {
  if (gameserveraddress != nullptr) {
    
  } else {
    
  }
  _impl_.gameserveraddress_.SetAllocated(gameserveraddress, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.gameserveraddress_.IsDefault()) {
    _impl_.gameserveraddress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.LoginResponsePacket.gameServerAddress)
}

// int32 gameServerPort = 4;
inline void LoginResponsePacket::clear_gameserverport() {
  _impl_.gameserverport_ = 0;
}
inline int32_t LoginResponsePacket::_internal_gameserverport() const {
  return _impl_.gameserverport_;
}
inline int32_t LoginResponsePacket::gameserverport() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginResponsePacket.gameServerPort)
  return _internal_gameserverport();
}
inline void LoginResponsePacket::_internal_set_gameserverport(int32_t value) {
  
  _impl_.gameserverport_ = value;
}
inline void LoginResponsePacket::set_gameserverport(int32_t value) {
  _internal_set_gameserverport(value);
  // @@protoc_insertion_point(field_set:Protocol.LoginResponsePacket.gameServerPort)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Packet_2eproto
